/* ============================================================
   Gratteri Ambassadors — AI Tour Guide data
   Researched and verified via web sources, July 2026.
   Categories: village | nature | towns | beach | food | wine | daytrip
   ============================================================ */

window.EXPLORE_DATA = [
  // ---------- In & around Gratteri ----------
  {
    name: "Grotta Grattara & the Nymph's Spring",
    emoji: "🧙",
    category: "village",
    distance: "25 min walk uphill (or 5 min drive + short walk)",
    effort: "easy",
    season: "year-round",
    blurb: "The cave that (probably) gave Gratteri its name is the legendary home of 'a Vecchia Strina' — Gratteri's own Befana — and hides a natural stone basin carved by millennia of dripping water.",
    details: "The cave gapes in the cliffs of Pizzo di Pilo just above the village, reached by a winding path from the Piano San Nicola picnic area through a fragrant pine wood, past a rock formation locals call the 'lazzu di voi' (oxen's bed). Inside, a crater-like boulder holds a basin shaped entirely by dripping water, which tradition holds to be purgative and restorative — the 'nymph's spring'. Legend says the old woman of the cave slips down the village chimneys on New Year's Eve to fill children's stockings, a story still celebrated in town. The mouth of the cave doubles as a natural balcony over the rooftops of Gratteri and the Tyrrhenian coast. Wear proper shoes — the final stretch is rocky — and combine it with the San Giorgio loop hike for a half-day outing. The pineta around it is a lovely spot for a picnic with kids.",
    maps_query: "Grotta Grattara, Gratteri",
    sources: ["https://www.visitgratteri.com/en/experience/the-grattaras-cave-park-and-excursions-in-the-pinewood/", "https://cefalu.it/en/things-to-do-en/grotta-grattara-park-discovering-the-fountain-of-the-ninfa/"],
  },
  {
    name: "Abbazia di San Giorgio (Norman abbey ruins)",
    emoji: "🛡️",
    category: "village",
    distance: "30 min walk from town (or short drive + walk)",
    effort: "easy",
    season: "year-round",
    blurb: "A ruined Norman abbey in the woods founded by Roger II around 1140 — the only Premonstratensian house ever built in Sicily, wrapped in Knights of Malta and even Holy Grail legends.",
    details: "Roger II is said to have founded this abbey around 1140 to seal peace with Pope Innocent II, entrusting it to white-robed French Premonstratensian canons; around 1300 it passed to the Knights Hospitaller of Jerusalem (later Knights of Malta), who held it as a commandery for centuries. The surviving walls trace a three-nave basilica with three apses, and its pilaster decoration echoes Cefalù's cathedral, built in the same years. Local lore claims hidden treasure and even the Holy Grail were sought among the ruins by mysterious foreigners — a story your kids will love on the walk out. The classic way to visit is the marked Gratteri loop trail (about 6 km, roughly 300 m of climb, 2-2.5 hours) that links the abbey, the San Giorgio wood and the Grotta Grattara. The Hospitallers' legacy lives on in town too: Via Ospedale is named for their pilgrims' hospital, and the cult of Saint James they brought is still felt. Go late afternoon for golden light on the stones.",
    maps_query: "Abbazia di San Giorgio, Gratteri",
    sources: ["https://www.visitgratteri.com/en/history-of-the-monastery-of-san-giorgio-the-only-house-of-the-premonstratensians-in-sicily/", "https://www.alltrails.com/trail/italy/sicily/gratteri-abbazia-san-giorgio"],
  },
  {
    name: "Gratteri old town: Chiesa Madre, belvedere & medieval lanes",
    emoji: "🏘️",
    category: "village",
    distance: "in town",
    effort: "easy",
    season: "year-round",
    blurb: "A maze of Arab-Norman lanes hiding relics said to come from Jerusalem — including four thorns of Christ's crown — and a belvedere nicknamed 'the balcony on the Tyrrhenian Sea'.",
    details: "Start at the 19th-century Chiesa Madre di San Michele Arcangelo (consecrated 1854), whose Ventimiglia chapel guards relics brought back from the Holy Land: four thorns said to be from the crown of Christ, a fragment of the Cross and a rib-bone relic of Saint James — a legacy of the village's Knights Hospitaller past. From Belvedere Ganci Battaglia the view sweeps over the coast to Cefalù, and on the clearest days you can pick out the Aeolian Islands. Seek out the Fontana della Ninfa, once topped by a nude nymph statue that spouted water from her breasts — the village's pagan 'genius loci'. Along Via Fiume, three medieval bridges and the Fantina well survive from when the Crati stream ran openly through town; it still flows beneath the street, dividing the oldest quarter from the newer one. Wander without a map — the lanes converge naturally on the Chiesa Madre square, and the older Matrice Vecchia is worth a peek if open (check locally).",
    maps_query: "Chiesa Madre San Michele Arcangelo, Gratteri",
    sources: ["https://www.visitgratteri.com/en/experience/chiesa-madre-and-the-treasures-of-jerusalem/", "https://www.visitcefalu.com/en/discovering-the-treasures-of-gratteri-the-most-mysterious-village-in-the-madonie/"],
  },
  {
    name: "Festa della Vecchia (New Year's Eve)",
    emoji: "🎭",
    category: "village",
    distance: "in town",
    effort: null,
    season: "winter (31 December)",
    blurb: "Gratteri's Befana doesn't wait for Epiphany: on New Year's Eve a masked 'Old Woman' rides a donkey through the lanes, handing out sweets and putting the old year on trial.",
    details: "Unique to Gratteri, 'a Vecchia Strina' descends from her home in the Grotta Grattara on the last night of the year rather than on January 6th. A masked figure hidden under a white sheet rides a donkey through the village, escorted by shouting boys, distributing 'turtigliuna' — buccellato-like pastries stuffed with almonds, hazelnuts, walnuts and dried figs. The procession culminates in the 'vanniata', a mock public trial of the year just ended, riffing on village and world events. Folklorists link the figure to the Roman goddess Strenia and ancient rites of gift-exchange and year-renewal, making this one of the most archaic surviving festivals in the Madonie. If your family is at the house over New Year, this is the night to be in the piazza; dress warmly, as Gratteri sits at about 650 m. Dates and format can vary year to year, so check locally or with the comune.",
    maps_query: "Piazza Ungheria, Gratteri",
    sources: ["https://www.visitgratteri.com/en/a-vecchia-end-of-year-event/", "https://www.enjoysicilia.it/en/curiosities/leggenda-vecchia-strina/"],
  },
  {
    name: "Abbazia di Santa Maria del Pedale walk",
    emoji: "🌿",
    category: "village",
    distance: "45-60 min walk from town",
    effort: "moderate",
    season: "spring & autumn",
    blurb: "The quieter sibling of San Giorgio: remains of an abbey founded around 1130 by Byzantine-rite Basilian monks, tucked into green valley country below the village.",
    details: "Said to be one of the oldest monastic foundations in Sicily, Santa Maria del Pedale was established around 1130 by Basilian monks of the Byzantine rite and later passed to the Benedictines — evidence of how many monastic orders converged on tiny Gratteri in the Middle Ages. It features on guided 'roads, knights and medieval monastic orders' walking itineraries that string together the Grotta Grattara, San Giorgio and Pedale along what is believed to be an ancient Roman-era road, so history-minded families can do all three in one epic day. The setting — pasture, oak woods and the Valle del Berillo — is as much the point as the stones. Paths are unevenly marked, so download an offline track (Wikiloc has local routes) or join a local guided excursion via the visitgratteri events pages. Spring brings wildflowers and running springs; autumn gives the best walking temperatures. Combine with a picnic and you've got Gratteri's landscape and its medieval story in a single walk.",
    maps_query: "Santa Maria del Pedale, Gratteri",
    sources: ["https://eventi.visitgratteri.com/en/on-foot/grattara-cave-abbeys-of-san-giorgio-and-santa-maria-del-pedale-discovering-roads-knights-and-medieval-monastic-orders/", "https://www.gratteriholiday.com/en/nature-walks-and-hikes-in-gratteri/"],
  },
  {
    name: "Santuario di Gibilmanna",
    emoji: "⛪",
    category: "village",
    distance: "15 min drive",
    effort: "easy",
    season: "year-round",
    blurb: "Sicily's beloved mountain sanctuary of the Madonna — founded, tradition says, on a monastery built by Pope Gregory the Great, and revived by a Capuchin friar from Gratteri itself.",
    details: "Perched at about 800 m on the wooded slopes of Pizzo Sant'Angelo, Gibilmanna is one of Sicily's great Marian shrines: tradition traces it to one of six monasteries founded by Gregory the Great in the 6th century, and its miraculous Madonna statue is tied to a legend of a storm-wrecked ship and an ox-cart that stopped here of its own accord. There's a proud local connection — the Capuchin convent was founded in 1535 by Father Sebastiano Majo, a native of Gratteri. In 1954 Pius XII declared the Madonna of Gibilmanna patroness of the Cefalù diocese, and the September 8 pilgrimage still draws crowds from across the Madonie. Don't miss the Museo Fra Giammaria in the old convent workshops and stables, ten rooms of Franciscan art gathered from Capuchin houses across the region. The terrace in front of the church is a superb natural balcony over the coast, and the drive back to Gratteri via the panoramic road is a treat in itself.",
    maps_query: "Santuario di Gibilmanna",
    sources: ["https://en.wikipedia.org/wiki/Sanctuary_of_Gibilmanna", "https://www.wondersofsicily.com/gibilmanna.htm"],
  },
  {
    name: "Isnello village & gorge",
    emoji: "🏞️",
    category: "village",
    distance: "15 min drive",
    effort: "easy",
    season: "year-round",
    blurb: "Gratteri's neighbour squeezed into a limestone gorge, with castle ruins on a crag, medieval churches and caves — a perfect slow afternoon wander.",
    details: "Isnello huddles beneath dolomitic cliffs where its stream has cut a dramatic narrow canyon between the castle rock and the wall of Montagna Grotta Grande. Climb to the ruins of the medieval castle on its rocky spur — best at sunset, when the last light turns the walls and gorge red. In the lanes below you'll find the 15th-century Chiesa Madre and the 14th-century Santa Maria Maggiore with its distinctive bell tower, part of the village's Arab-Norman fabric. Cavers know Isnello for the Abisso del Vento, one of Sicily's most important cave systems with white stalactites and flowstone — but note it is strictly for equipped speleologists with guides, not a walk-in attraction. The village is also a trailhead for walks toward Pizzo Dipilo and a marked Gratteri-Isnello path links the two villages on foot. Pair the visit with an evening at the GAL Hassin astronomical park just outside town.",
    maps_query: "Isnello, Sicily",
    sources: ["https://www.enjoysicilia.it/en/cefalu-parco-madonie/isnello/", "https://www.lasiciliainrete.it/en/directory-tangibili/listing/abisso-del-vento/"],
  },
  {
    name: "GAL Hassin astronomical park (Isnello)",
    emoji: "🔭",
    category: "village",
    distance: "15-20 min drive",
    effort: "easy",
    season: "year-round (clear nights; best in summer)",
    blurb: "One of Europe's most advanced public astronomy centres sits in Gratteri's back yard — evening stargazing run by real astrophysicists under some of Italy's darkest skies.",
    details: "Just past neighbouring Isnello, GAL Hassin (opened 2016) is both a working research centre — part of the International Astronomical Union network, with its Wide-field Mufara Telescope station up at 1,865 m ranking among the highest observing stations in Italy — and a superb visitor attraction. The public campus has a planetarium under a 10 m dome, an observation terrace with a retractable roof and a battery of twelve telescopes, plus an open-air 'solar lab' of sundials and a monumental globe. Evening sessions let families view planets, nebulae and the Moon through the big instruments with astronomers on hand; the Madonie's low light pollution makes for genuinely dark skies. Check the programme and book ahead on galhassin.it, as night openings follow a calendar and fill up in summer — and check whether the session runs in English or Italian. Nights are chilly at altitude even in August, so bring layers. The name comes from the Arabic for Isnello, a nod to Sicily's Arab astronomical heritage.",
    maps_query: "GAL Hassin, Isnello",
    sources: ["https://galhassin.it/en/", "https://cefalu.it/en/things-to-do-en/in-isnello-look-up-and-be-amazed-by-the-stars/"],
  },
  {
    name: "Collesano: Targa Florio museum & maiolica",
    emoji: "🏎️",
    category: "village",
    distance: "20 min drive",
    effort: "easy",
    season: "year-round",
    blurb: "The world's oldest sports-car race thundered through these medieval streets from 1906 to 1977 — Collesano keeps the Targa Florio flame alive, alongside a revived hand-painted ceramics tradition.",
    details: "The Museo Targa Florio, founded in 2004 on the main street, is a shrine to the legendary road race run on the public roads of the Madonie: bronze plaques, drivers' helmets, suits, gloves and photographs from the era when Porsche and Ferrari works teams raced past front doors. The town itself was a corner of the Circuito Piccolo delle Madonie, and petrolheads can still drive the old circuit roads toward Campofelice and Cerda — the successor Targa Florio rally uses them to this day. Collesano's other claim is maiolica: a distinctive centuries-old pottery style that died out and is now being revived by artisan workshops, with ceramic plaques dotted around the old town. Climb the monumental staircase to the 16th-century Basilica di San Pietro to see the spectacular painted crucifix of 1555 hanging in the nave. Museum opening can be limited off-season, so check before driving over.",
    maps_query: "Museo Targa Florio, Collesano",
    sources: ["https://www.wondersofsicily.com/collesano.htm", "https://en.wikipedia.org/wiki/Circuito_delle_Madonie"],
  },

  // ---------- Madonie & nature ----------
  {
    name: "Pizzo Sant'Angelo hike",
    emoji: "⛰️",
    category: "nature",
    distance: "15 min drive to Gibilmanna trailhead",
    effort: "moderate",
    season: "year-round (start early in summer)",
    blurb: "Said to be one of the best lookout peaks in northern Sicily — a forested climb from Gibilmanna sanctuary to a summit with the sea on one side and the Madonie giants on the other.",
    details: "The popular route starts near the Gibilmanna sanctuary and climbs about 7.4 km round trip with roughly 230 m of elevation gain — around 2 hours' walking through holm-oak forest and Mediterranean scrub. Though modest in height (around 1,080 m), the peak towers over the Isnello valley and gives a sweeping panorama: the Tyrrhenian coast and Cefalù one way, and the Carbonara, Cervi and Dipilo massifs of the Madonie the other. The final stretch is rocky and pebbly, so sturdy shoes help; poles are handy for the descent. Combine it with a visit to the sanctuary at the trailhead for an easy half-day. In summer go at dawn or late afternoon — the shade cover is good but the summit is exposed. Winter days can be spectacular for visibility toward the Aeolian Islands.",
    maps_query: "Pizzo Sant'Angelo, Madonie",
    sources: ["https://www.summitpost.org/pizzo-sant-angelo/215255", "https://www.komoot.com/guide/502591/hiking-around-parco-delle-madonie"],
  },
  {
    name: "Pizzo Dipilo summit",
    emoji: "🦅",
    category: "nature",
    distance: "trailheads at town edge",
    effort: "challenging",
    season: "spring & autumn",
    blurb: "The bare limestone dome looming 1,385 m above Gratteri — a wild karst summit where kites and vultures once nested, with the whole Tyrrhenian coast at your feet.",
    details: "Pizzo Dipilo (also written 'di Pilo') is the mountain whose flanks hold the Grotta Grattara; its grey dolomitic mass dominates every view from the village. A loop trail circles the summit area starting from Gratteri, mostly on marked paths, while another classic approach comes up from Isnello with a scramble along the south ridge — either way expect rough karst terrain, little shade and a proper mountain day. The reward is one of the finest 360-degree panoramas in the northern Madonie, over the coast, Cefalù's Rocca and the high peaks around Pizzo Carbonara. Historically kites and vultures nested here, and griffon vultures have been reintroduced in the Madonie park, so keep an eye on the thermals. Take plenty of water, and avoid the exposed summit in high summer heat or low cloud. Less confident walkers can hire a local Madonie park guide — worth it for the karst 'craters' and cave lore on the way up.",
    maps_query: "Pizzo Dipilo",
    sources: ["https://www.summitpost.org/pizzo-dipilo/218326", "https://www.visitgratteri.com/en/experience/di-pilo-lace-and-its-craters/"],
  },
  {
    name: "Piano Battaglia",
    emoji: "⛷️",
    category: "nature",
    distance: "50 min drive",
    effort: "easy",
    season: "year-round",
    blurb: "Sicily's improbable little ski station at 1,600 m — snowball fights with a distant view of the sea in winter, cool high-mountain hiking base in summer.",
    details: "Piano Battaglia sits in a glacial-looking bowl between Pizzo Carbonara and Monte Mufara, and is western Sicily's only ski area, with a lift up Monte Mufara (1,865 m) and beginner-to-intermediate pistes such as the roughly 3 km Sparviero run. In snowy spells (typically January–February) Palermitani flood up for skiing, sledging and snowman-building, so arrive early on winter weekends and carry snow chains — they're often mandatory on the mountain roads. In summer it flips into the main trailhead hub of the Madonie, with marked walks in every direction and mountain rifugi serving hearty lunches. The drive from Gratteri via Isnello and Piano Zucchi is a beautiful winding climb in its own right. Check snow conditions and lift status locally before a winter trip, as openings depend entirely on snowfall.",
    maps_query: "Piano Battaglia, Petralia Sottana",
    sources: ["https://www.petraliavisit.it/en/piano-battaglia-winter-sports-and-ski-runs/", "https://www.enjoysicilia.it/en/cefalu-parco-madonie/parco-delle-madonie/piano-battaglia-madonie/"],
  },
  {
    name: "Pizzo Carbonara",
    emoji: "🏔️",
    category: "nature",
    distance: "50 min to trailhead",
    effort: "moderate",
    season: "spring-autumn",
    blurb: "Summit Sicily's second-highest peak (1,979 m) — a half-day walk through a lunar karst landscape with views said to stretch from the Tyrrhenian Sea to Etna.",
    details: "The classic route starts from the parking areas at Piano Battaglia on the SP54 and climbs past Pizzo Scalonazzo through dolines, sinkholes and wind-sculpted beech woods to the broad summit plateau. A reasonably fit walker does the round trip in roughly 2.5–4 hours; no technical skill is needed, but the rocky karst underfoot is uneven and the plateau is famously misty, so navigation gets genuinely hard in cloud. Go on a clear day, download the GPX track (the AllTrails 'Piano Battaglia – Pizzo Carbonara' route is well reviewed), and bring layers — it can be 15 degrees cooler than the coast. Late spring brings wildflowers and grazing cattle; autumn gives the clearest air for spotting Etna on the horizon. There is no water on the route, so carry plenty.",
    maps_query: "Piano Battaglia parking Pizzo Carbonara trailhead",
    sources: ["https://en.wikipedia.org/wiki/Pizzo_Carbonara", "https://www.alltrails.com/trail/italy/sicily/piano-battaglia-pizzo-carbonara"],
  },
  {
    name: "Gole di Tiberio",
    emoji: "🛶",
    category: "nature",
    distance: "45 min drive",
    effort: "moderate",
    season: "summer",
    blurb: "Drift by dinghy through a 400 m limestone slot canyon on the Pollina river — a UNESCO Geopark site with 50 m walls, eels, dragonflies and swimming holes.",
    details: "This hidden gorge, carved through Upper Triassic limestone around 200 million years old, is run as guided small-boat excursions (roughly 2 hours) from May to September, combining the dinghy passage with a walk and swims along the Pollina river; in the cooler months operators switch to rafting and river-trekking descents in wetsuits. Guides point out fossil gastropods in the rock, bee-eaters and grey wagtails, and a boulder passage said to have been used by brigands. The base area has changing rooms, showers, a bar and picnic/barbecue spots, so it works well as a full family day. Book ahead in July–August through the official goleditiberio.com operator, wear water shoes, and bring a dry bag for phones. Kids generally love it — check minimum ages with the operator when booking.",
    maps_query: "Gole di Tiberio, Pollina river",
    sources: ["https://goleditiberio.com/", "https://cefalu.it/en/things-to-do-en/a-rafting-trip-through-the-gorges-of-tiberio/"],
  },
  {
    name: "Zipline Sicilia (San Mauro Castelverde)",
    emoji: "🪂",
    category: "nature",
    distance: "1 hr drive",
    effort: "easy",
    season: "spring-autumn",
    blurb: "Sicily's first giant zipline: a 1,600 m 'angel flight' face-down over a Madonie valley at up to 130 km/h, with the Tyrrhenian Sea on the horizon.",
    details: "From the hilltop village of San Mauro Castelverde you're harnessed horizontally, superman-style, and launched down a single 1.6 km steel cable that drops about 260 m (from 925 m to 669 m altitude), flying up to roughly 170 m above the ground for about a minute and a half. Tandem 'lancio doppio' flights are offered, so parents can fly alongside kids — check current age/weight limits and book via ziplinesicilia.it, especially on summer weekends. The village itself, one of the highest in the Madonie, has an ancient centre and big sea-to-mountain views worth a wander after your flight, and the same area is the gateway to the Gole di Tiberio below. Flights depend on wind, so keep plans flexible and reconfirm on the day. Combine both for one of the best adventure days in northern Sicily.",
    maps_query: "Zipline Sicilia, San Mauro Castelverde",
    sources: ["https://www.ziplinesicilia.it/", "https://www.sicilying.com/en/experiences/nature/Adventure-parks/en-zip-line-Sanmauro-Castelverde-1171"],
  },
  {
    name: "Parco Avventura Madonie",
    emoji: "🌳",
    category: "nature",
    distance: "55 min drive",
    effort: "moderate",
    season: "summer",
    blurb: "Sicily's first high-ropes adventure park — around 80 tree-top games in the mountain woods above Petralia Sottana, from toddler trails to athlete-grade courses.",
    details: "Opened in 2008 at contrada Gorgonero on the road between Petralia Sottana and Piano Battaglia, this was Sicily's original adventure park and remains the benchmark: roughly ten aerial courses of graded difficulty with about 80 bridges, nets, Tarzan swings and ziplines strung between the trees, all done in harness after a safety briefing. Beyond the ropes there's archery, orienteering, guided trekking, mountain-bike routes and even 'suspended tent' overnight stays seven metres up with transparent roofs for stargazing. Courses exist for small children as well as adults, so mixed-age families are well served; wear closed shoes and tie hair back. Summer weekends get busy — call or message ahead (the park operates seasonally, roughly spring to autumn) to confirm opening and reserve. It combines naturally with a Piano Battaglia walk or a Petralia village visit for a full mountain day.",
    maps_query: "Parco Avventura Madonie, Petralia Sottana",
    sources: ["https://www.parcoavventuramadonie.it/", "https://www.parks.it/parco.madonie/indotto_dettaglio.php?id=1032"],
  },

  // ---------- Historic towns ----------
  {
    name: "Castelbuono",
    emoji: "🏰",
    category: "towns",
    distance: "35 min drive",
    effort: "easy",
    season: "year-round",
    blurb: "The lively capital of the Madonie: a 1317 Ventimiglia castle, the pastry empire behind Italy's most coveted panettone, and Europe's last manna harvest.",
    details: "Start at the Castello dei Ventimiglia, built in 1317 by Count Francesco I Ventimiglia, now the civic museum with a famously stucco-encrusted Palatine chapel. Around Piazza Margherita, the Fiasconaro pasticceria (founded 1953) is the pilgrimage stop — their panettone is exported worldwide and even flew to the International Space Station; try anything made with manna, the sweet ash-tree sap that only Castelbuono and neighbouring Pollina still harvest by hand, and pick up manna chunks in the food shops. Don't miss the Museo Naturalistico Minà Palumbo, a wonderfully old-school natural history collection of Madonie flora and fauna assembled by a 19th-century local doctor-naturalist. Every August the town hosts Ypsigrock, Italy's original boutique indie festival, with the main stage set beneath the castle walls — book accommodation far ahead if visiting then. Come hungry: Castelbuono has some of the best restaurants in the mountains.",
    maps_query: "Castello dei Ventimiglia, Castelbuono",
    sources: ["https://fiasconaro.com/en/", "https://www.ypsigrock.it/en/festival/"],
  },
  {
    name: "Pollina",
    emoji: "🎭",
    category: "towns",
    distance: "35 min drive",
    effort: "easy",
    season: "summer",
    blurb: "A tiny eagle's-nest village at 730 m with a Greek-style stone theatre on its summit — sunset concerts between the Madonie peaks and the sea.",
    details: "Pollina's houses cling to a rock high above the Tyrrhenian coast, a short but spectacular drive from Gratteri, with stone-paved lanes leading up past small churches to the remains of a tower and castle at the top. There sits the Teatro Pietra Rosa, an open-air theatre built in 1979 to a design by Venetian architect Antonio Foscari in homage to classical Greek theatres — its backdrop takes in Castelbuono, Geraci and the mountains, and summer evening performances here are magical (check the 'I Classici del Pietra Rosa' season locally). Pollina shares with Castelbuono the distinction of being the only place in the Mediterranean still producing manna from ash trees, and its small Museo della Manna explains the harvest with tastings and products to buy. Go late afternoon, wander, catch the sunset from the theatre terrace, then dine back down the hill. In high summer, pair it with a swim at Finale di Pollina on the coast below.",
    maps_query: "Teatro Pietra Rosa, Pollina",
    sources: ["https://www.enjoysicilia.it/en/cefalu-parco-madonie/pollina/", "https://www.tripadvisor.com/Attraction_Review-g2270442-d10148952-Reviews-Museo_della_Manna-Pollina_Province_of_Palermo_Sicily.html"],
  },
  {
    name: "Geraci Siculo",
    emoji: "🦅",
    category: "towns",
    distance: "55 min drive",
    effort: "easy",
    season: "year-round",
    blurb: "The old Ventimiglia mountain capital with a vertigo-inducing glass walkway jutting over the cliff where a count and his blindfolded horse leapt into legend.",
    details: "Geraci Siculo, one of the 'Borghi più Belli d'Italia', was the medieval seat of the Ventimiglia counts before Castelbuono, and keeps a proper mountain-borgo feel: castle ruins on the crag, narrow winding alleys and churches wedged between houses. Its showpiece is the Salto dei Ventimiglia, a steel-and-glass platform (opened 2014) projecting about three metres over the ravine where, legend says, Count Francesco I Ventimiglia rode his blindfolded horse off the cliff in 1337 rather than be captured by royal troops — the view sweeps east toward Etna. The town is also famous for its water: springs high in the park feed both the public fountains and the bottled 'Acqua Geraci' brand, so fill your bottles like the locals do. Note the 'salto' here is a viewpoint, not a zipline — the big zipline is at San Mauro Castelverde. It slots perfectly into a day loop with Castelbuono (20 minutes north) or Gangi (further along the SS286/SS120).",
    maps_query: "Salto dei Ventimiglia, Geraci Siculo",
    sources: ["https://visitgeracisiculo.it/il-salto-dei-ventimiglia/", "https://www.acquageraci.it/"],
  },
  {
    name: "Petralia Soprana & the salt mine",
    emoji: "🧂",
    category: "towns",
    distance: "1 hr drive",
    effort: "easy",
    season: "year-round",
    blurb: "Italy's 'most beautiful village' of 2018 at 1,100 m — with a working rock-salt mine beneath it hiding a contemporary art museum carved in salt.",
    details: "Petralia Soprana won RAI's 'Borgo dei Borghi' title in 2018 and earns it: stone lanes, baroque churches with Serpotta stuccos, and three belvederes (Loreto, Carmine and Piazza Duomo) looking out to Etna and half of inland Sicily. Below the village at Raffo, the Italkali mine works a vast deposit of pure rock salt — over 80 km of tunnels — left when the Mediterranean dried out around six million years ago. Inside a disused gallery is MACSS, the 'Museo Sotto Sale', a genuinely unique museum of about forty salt sculptures created during art biennials since 2011; guided visits include helmets and a waiver since it's an active mine. Visits run on limited days and booking is mandatory (historically by email to the SottoSale association), so arrange it well ahead. Pair the underground tour with lunch in the village and a belvedere passeggiata.",
    maps_query: "Petralia Soprana",
    sources: ["https://www.museosottosale.it/en/an-art-museum-in-the-mine/", "https://borghipiubelliditalia.it/en/borgo/petralia-soprana/"],
  },
  {
    name: "Petralia Sottana",
    emoji: "🏘️",
    category: "towns",
    distance: "55 min drive",
    effort: "easy",
    season: "year-round",
    blurb: "Soprana's elegant twin down the hill — an Orange Flag borgo of baroque churches and cobbled lanes that doubles as the gateway town to the high Madonie.",
    details: "Petralia Sottana is one of the 'Borghi più Belli d'Italia' and holds the Touring Club's Orange Flag for hospitality; its corso threads past the Chiesa Madre and San Giovanni Battista to lookout points over the Imera valley. It's the natural service town for the southern Madonie: the road up to Piano Battaglia starts here, and the town is closely tied to the park and its UNESCO Geopark identity, with small museums covering local geology and archaeology. In August the town stages the 'Ballo della Cordella', a historic harvest dance festival, said to be one of the Madonie's most authentic traditions. Combine with Petralia Soprana, 10 minutes up the hill, and the Parco Avventura on the Piano Battaglia road for a full mountain day.",
    maps_query: "Petralia Sottana",
    sources: ["https://www.italia.it/en/sicily/petralia-sottana", "https://www.parcoavventuramadonie.it/"],
  },
  {
    name: "Gangi",
    emoji: "🌄",
    category: "towns",
    distance: "1 hr 15 min drive",
    effort: "moderate",
    season: "year-round",
    blurb: "The village that won 'most beautiful in Italy' in 2014 — a perfect cone of stone houses stacked on a hill, staring straight at Mount Etna.",
    details: "Gangi beat every other borgo in Italy in RAI's 2014 'Borgo dei Borghi' public vote, and its skyline — concentric rings of medieval houses wrapping a hilltop — is one of Sicily's great sights, best photographed from the approach road. Inside, climb to the Ventimiglia tower (now the bell tower of the Chiesa Madre), peek into some of its 18 churches, and visit Palazzo Bongiorno's frescoed halls and Palazzo Sgadari's small civic museums. Piazza del Popolo's belvedere looks over the valley, and on clear days Etna dominates the horizon. It's the farthest of the classic Madonie borghi from Gratteri, so make it a full day, ideally looping back via Geraci Siculo on the SS286. In August the Sagra della Spiga wheat festival fills the streets, and at Christmas a large living nativity takes over the old town.",
    maps_query: "Gangi, Sicily",
    sources: ["https://www.italiannotebook.com/places/gangi/", "https://www.bed-and-breakfast.it/it/news/il-borgo-dei-borghi-in-italia-e-gangi/1279"],
  },
  {
    name: "Polizzi Generosa & the world's rarest fir",
    emoji: "🌲",
    category: "towns",
    distance: "50 min drive",
    effort: "moderate",
    season: "spring-autumn",
    blurb: "A 'generous' borgo on a spur of the western Madonie, home of the sfoglio cheese-cake — and gateway to the valley hiding the ~30 last wild Madonie firs on Earth.",
    details: "Polizzi Generosa (the epithet was reputedly bestowed by Frederick II) perches dramatically above the Imera valley with churches, palazzi and big views; its culinary claim to fame is lo sfoglio, a pastry filled with fresh tuma cheese, sugar, cinnamon and chocolate that you should buy from a village pasticceria. Above town, the road towards the Quacella amphitheatre reaches the trail into the Vallone Madonna degli Angeli, where botanists in 1957 rediscovered Abies nebrodensis — the Madonie fir, thought extinct, now surviving as roughly 30 wild adult trees between 1,400 and 1,650 m and ranked among the most endangered conifers in the world. The marked 'Sentiero degli Abies nebrodensis' lets you walk among numbered, individually monitored specimens; going with a local guide adds a lot, and a small museum in town tells the species' story. Landscapes shift within a few hundred metres from holm oak to beech and holly, making this one of the park's most interesting botanical walks. Spring and autumn are best; the trail is high, so pack warm layers.",
    maps_query: "Polizzi Generosa",
    sources: ["https://www.cefalumadoniehimera.it/abies-nebrodensis/?lang=en", "https://visitpolizzigenerosa.it/it/itinerari/sentiero-abies-nebrodensis-zona-a-del-parco-delle-madonie/"],
  },

  // ---------- Coast & beaches ----------
  {
    name: "Cefalù town beach (Lungomare)",
    emoji: "🏖️",
    category: "beach",
    distance: "25 min drive",
    effort: "easy",
    season: "May-October",
    blurb: "The postcard: a long crescent of golden sand with the medieval old town and La Rocca rising straight out of the water at one end.",
    details: "Cefalù's main beach runs the length of the Lungomare — fine sand, water that stays shallow a long way out (ideal for small children), and that famous view back over rooftops to the crag. It mixes free stretches with lidos offering sunbeds, umbrellas and showers; the eastern end nearest the old town is prettiest and busiest. In July and August arrive before 9:30 or expect to circle for parking — or park at the station end and walk. Late afternoon the light on the old town turns gold and the crowds thin; evening swims here, with dinner in the lanes afterwards, are the classic Cefalù day. Storm days in the off-season are spectacular from the seafront rail.",
    maps_query: "Spiaggia di Cefalù Lungomare",
    sources: ["https://www.thewomtravel.com/italy/sicily/palermo/best-cefalu-beaches.html", "https://cefalu.it/en/magazine-en/the-enchanting-beauty-of-the-beaches-of-cefalu/"],
  },
  {
    name: "Caldura cove",
    emoji: "🤿",
    category: "beach",
    distance: "30 min drive + 20 min walk past the port",
    effort: "moderate",
    season: "June-September",
    blurb: "Cefalù's snorkelling cove: dark pebbles, water that turns deep and glass-clear within a few steps, and far fewer people than the sands.",
    details: "Caldura sits east of Cefalù's Porto Presidiana, reached on foot past the marina — which is exactly why it stays quieter than the town beach. The shore is gravel and dark pebbles, the seabed drops quickly, and the water clarity is the best close to town: bring masks and snorkels, and water shoes make entry far more comfortable. It's a swimmers' and teenagers' beach more than a toddlers' one — the deep water is the point. There's little natural shade and facilities are minimal, so carry water and an umbrella, or time it for late afternoon when the cliff shadow arrives. Pair it with a look at the fishing boats in the port on the walk back.",
    maps_query: "Spiaggia Caldura Cefalù",
    sources: ["https://www.thewomtravel.com/italy/sicily/palermo/best-cefalu-beaches.html", "https://cefalu.it/en/magazine-en/the-enchanting-beauty-of-the-beaches-of-cefalu/"],
  },
  {
    name: "Mazzaforno & Settefrati coves",
    emoji: "🐚",
    category: "beach",
    distance: "about 20 min drive",
    effort: "easy",
    season: "May-October",
    blurb: "Gratteri's own cove country: the first swims you reach on the coast road, mixing wild corners, beach clubs, and seven legendary rock stacks.",
    details: "West of Cefalù on the Gratteri side, the Mazzaforno stretch breaks into a series of sand-and-pebble coves backed by greenery — some wild and free, some with lidos where you can rent beds and eat lunch with your feet in the sand. Next along, Settefrati takes its name from seven rock stacks rising from the sea, tied to a local legend of seven brothers who drowned rescuing a sister; the rocks make for superb snorkelling and the sunsets behind them are the best on this stretch. Because you reach these before Cefalù itself, they're the smart choice on busy August days — you skip the town traffic entirely. Access paths from the coast road can be steep or rough in the wild sections, so sandals with grip help. Water is generally calm and family-friendly, clearer over the pebble patches.",
    maps_query: "Spiaggia Settefrati Cefalù",
    sources: ["https://www.thewomtravel.com/italy/sicily/palermo/best-cefalu-beaches.html", "https://cefalu.it/en/magazine-en/the-enchanting-beauty-of-the-beaches-of-cefalu/"],
  },
  {
    name: "Salinelle & Capo Playa (the windsurf stretch)",
    emoji: "🪁",
    category: "beach",
    distance: "about 20 min drive",
    effort: "easy",
    season: "May-October (windiest afternoons)",
    blurb: "The breezy end of the great sand: kites and sails carving along Capo Playa while everyone else naps — the coast's free, roomy, sporty corner.",
    details: "Where the long Campofelice-Lascari sands meet Capo Playa, a dependable afternoon breeze funnels along the shore — which is why the windsurfers and kitesurfers gather here rather than under Cefalù's crag. The beach itself is wide, mostly free and never truly packed; bring your own umbrella and water as facilities are sparse away from the odd seasonal bar. For families it's a great 'active' beach: firm sand for games, shallow entry, and a constant show of kites out on the water. Mornings are calmer for swimming; the wind typically builds after lunch. If anyone in the family wants to learn, seasonal schools and rental setups appear along this stretch in summer — ask at the beach or check locally.",
    maps_query: "Capo Playa Salinelle kitesurf Lascari",
    sources: ["https://www.thewomtravel.com/italy/sicily/palermo/best-cefalu-beaches.html", "https://www.beachatlas.com/sand-beaches-campofelice-di-roccella"],
  },
  {
    name: "The long golden beach of Campofelice di Roccella",
    emoji: "🏄",
    category: "beach",
    distance: "about 20 min drive (straight downhill)",
    effort: "easy",
    season: "May-October",
    blurb: "The closest sand to Gratteri: roughly 10-12 km of golden beach running below the Lascari plain, with room to breathe even in mid-August.",
    details: "This is one of the longest beaches in Sicily, stretching from Capo Plaia near Lascari all the way to the mouth of the Imera river, with wide free sections alternating with lidos (sunbeds, showers, snack bars) around Campofelice's marina area. The sand is fine and golden, the water shallows gently, and the westward view means flaming sunsets over the mountains toward Palermo. Because it's directly below Gratteri's own plain, it's the easy 'after-school swim' beach — you can be on the sand faster than you can park in Cefalù. The Salinelle end near Capo Plaia catches more breeze and attracts windsurfers and kitesurfers. Free stretches have no facilities, so bring umbrellas and water, or pick a lido and settle in for the day.",
    maps_query: "Spiaggia Campofelice di Roccella",
    sources: ["https://www.sicilvill.com/en/experience-en-en/campofelice-di-roccella-beach/", "https://www.beachatlas.com/sand-beaches-campofelice-di-roccella"],
  },
  {
    name: "Boat trip along the Cefalù coast",
    emoji: "⛵",
    category: "beach",
    distance: "25 min drive to Cefalù port",
    effort: "easy",
    season: "roughly May-October",
    blurb: "See La Rocca and the old town from the water, then drop anchor in coves and sea caves you can't reach by road.",
    details: "Small-boat excursions leave from Cefalù's marina at Porto Presidiana, typically 3 hours with about half the time cruising past cliffs like Giudecca and Bastione and half at swim stops in bays such as Kalura, often including the Santa Lucia sea cave. Most tours include snorkel gear, fruit or a Sicilian aperitivo on board; sunset departures are the most atmospheric. Both shared and private charters exist — private skippered boats are worth it for families with young kids so you set the pace. Book a day or two ahead in July-August via the kiosks at the port or online platforms; seas are usually calmest in the morning. Bring reef-safe sunscreen and a towel per person, and check the operator's policy if the forecast turns windy.",
    maps_query: "Porto Presidiana Cefalù boat tours",
    sources: ["https://www.getyourguide.com/cefalu-l2176/cruises-boat-tours-tc48/", "https://cefaluboattours.it/en/home-en/"],
  },
  {
    name: "Sant'Ambrogio hamlet & belvedere",
    emoji: "🌅",
    category: "beach",
    distance: "about 30-35 min drive",
    effort: "easy",
    season: "year-round",
    blurb: "A tiny stone hamlet stacked above the sea just east of Cefalù — locals' quiet beach below, Madonie behind, and one of the best sunset views on this coast.",
    details: "Sant'Ambrogio is a frazione of Cefalù about 7 km east of town, a knot of alleys and stone houses around a simple village church, with a west-facing belvedere that looks straight back at Cefalù and La Rocca — go for sunset. Below the village is a gravel-and-sand beach used mostly by locals, so it stays calm even in August. There's little 'to do' in the best way: coffee in the piazza, a wander through lanes with sudden sea views, and hearty local cooking (hand-made cavatelli, local salumi and cheeses) in the couple of trattorias — check opening days outside summer. It pairs naturally with a swim at Caldura or a drive on to Castelbuono. The village feast of Sant'Ambrogio is held on 7 December if you're there in winter.",
    maps_query: "Sant'Ambrogio Cefalù belvedere",
    sources: ["https://www.bmsuitescefalu.com/en/the-village-of-santambrogio/", "https://www.taliammari.it/en/news-en/santambrogio-a-hidden-village-near-cefalu/"],
  },
  {
    name: "Torre Conca & the Finale di Pollina coast",
    emoji: "🤿",
    category: "beach",
    distance: "about 40 min drive",
    effort: "easy",
    season: "summer for swimming; walks year-round",
    blurb: "A hidden inlet under a 16th-century watchtower where the water turns deep a few steps from shore — the locals' escape when Cefalù fills up.",
    details: "Torre Conca sits just below Capo Rais Gerbi, about 1 km east of the village of Finale di Pollina; a short path drops from the coast road to a beach of sand, dark gravel and pebbles named for the old coastal watchtower above. The seabed deepens quickly, which makes it one of the best snorkelling and diving spots on this stretch, and a breakwater means you can often swim even when the open sea is choppy. Access is free with parking along the road; in summer a small snack bar appears and pedal boats are said to be for hire, but bring your own water and shade to be safe. It's popular with locals from Pollina and Finale rather than tourists. Combine with lunch in Finale or a detour up to the spectacular hilltop village of Pollina itself.",
    maps_query: "Spiaggia Torre Conca Finale di Pollina",
    sources: ["https://www.lasiciliainrete.it/en/directory-tangibili/listing/spiaggia-di-torre-conca-finale-di-pollina/", "https://cefalu.it/en/magazine-en/a-trip-along-the-coast-of-pollina-to-discover-its-beaches/"],
  },
  {
    name: "Aeolian Islands day trip (Lipari & Vulcano)",
    emoji: "🌋",
    category: "beach",
    distance: "25 min to Cefalù + full-day excursion",
    effort: "moderate",
    season: "summer only (roughly June-September)",
    blurb: "From Gratteri's belvedere you can see the Aeolians on clear days — in summer you can actually stand on them: volcanic islands, black-sand beaches and thermal mud in a single epic day.",
    details: "Cefalù historically had a seasonal summer hydrofoil to the Aeolians, but that direct scheduled service is reported suspended in recent years — verify locally before planning around it. What runs reliably in season are organized full-day excursions sold in Cefalù: typically an early start, then boat to Lipari (citadel, archaeological museum, pretty waterfront for lunch) and Vulcano (steaming fumaroles, thermal mud baths, black-sand swimming); some itineraries instead do Panarea and an evening Stromboli eruption cruise. Note some operators coach you to Milazzo to board rather than sailing from Cefalù's port — check when booking. It is a long day (roughly 12 hours) best for kids ~6+. Book several days ahead in August, take seasickness tablets if in doubt, and pack swimwear plus a change of clothes — the sulphur smell on Vulcano clings.",
    maps_query: "Cefalù port Aeolian Islands excursions",
    sources: ["https://www.viator.com/tours/Sicily/Aeolian-Islands-Lipari-and-Vulcano-Day-Tour-from-Cefalu/d205-6552P11", "https://www.tripadvisor.com/ShowTopic-g194726-i1382-k15014716-Cefalu_to_Lipari_Summer_2025-Cefalu_Province_of_Palermo_Sicily.html"],
  },

  {
    name: "Castel di Tusa: the art coast (Fiumara d'Arte)",
    emoji: "🗿",
    category: "beach",
    distance: "about 45-50 min drive east",
    effort: "easy",
    season: "year-round (swims in summer)",
    blurb: "A pebble-beach village that doubles as the gateway to Europe's largest open-air sculpture park — monumental contemporary art scattered up a riverbed, plus a museum-hotel where the rooms are artworks.",
    details: "Castel di Tusa, a small maritime village east along the coast, is the sea end of Fiumara d'Arte: a trail of monumental contemporary sculptures created from the 1980s onward at the initiative of Sicilian philanthropist Antonio Presti, winding inland along the Tusa riverbed through villages like Motta d'Affermo, Pettineo and Castel di Lucio. Driving the circuit takes about an hour and turns a beach day into a treasure hunt — the great blue 'Energia Mediterranea' wave and the pyramid '38° Parallelo' on its ridge above the sea are the showstoppers. In the village itself, the Atelier sul Mare (opened 1991) is a museum-hotel right on the beach whose rooms were designed by artists — non-guests can ask about visiting the art rooms, and its terrace bar makes a good stop either way. The beaches here are clean pebbles with clear water, much quieter than Cefalù. Combine the sculptures, a swim and lunch in the village for one of the most unusual days on this coast.",
    maps_query: "Castel di Tusa Atelier sul Mare",
    sources: ["https://artsandculture.google.com/story/museum-hotel-atelier-sul-mare-fiumara-d-arte-fondazione-antonio-presti-energia-mediterranea-di-antonio-di-palma/NQXhmxbZCvxuKw?hl=en", "https://www.icastelli.net/en/art-hotel-atelier-sul-mare"],
  },
  {
    name: "Mondello (worth the drive)",
    emoji: "🩵",
    category: "beach",
    distance: "about 1h20 drive (beyond Palermo)",
    effort: "easy",
    season: "May-October",
    blurb: "Palermo's Belle Époque beach: a kilometre of white sand and Caribbean-turquoise shallows between two mountains, with a Liberty-style pier pavilion floating over the water.",
    details: "Mondello sits in a perfect half-moon bay between Monte Pellegrino and Capo Gallo just north of Palermo, and its pale sand and shallow turquoise water genuinely look airlifted from the tropics. The Art Nouveau bathing pavilion on stilts (the Antico Stabilimento Balneare, built in the early 1900s) gives the bay its famous silhouette. Summer brings serious crowds of Palermitani — go on a weekday, arrive early, and expect a mix of lidos and free stretches; out of season it's a gorgeous, breezy promenade town with seafood restaurants around the little square. It pairs naturally with a Palermo or Monreale morning: mosaics first, then an afternoon swim before the drive home. Kids love the shallow water; parents love the gelato kiosks. Parking in August requires patience — the paid lots near the square beat circling.",
    maps_query: "Spiaggia di Mondello Palermo",
    sources: ["https://en.wikipedia.org/wiki/Mondello"],
  },

  // ---------- Food & wine ----------
  {
    name: "Pasta 'a taianu — Cefalù's own dish",
    emoji: "🍝",
    category: "food",
    distance: "25 min drive (Cefalù trattorias)",
    effort: null,
    season: "year-round (its festival is early August)",
    blurb: "The dish Cefalù cooks for its patron saint: layered pasta, two meats, fried aubergine and pecorino, baked in the terracotta pot that gives it its Arabic name.",
    details: "Pasta 'a taianu takes its name from the 'taianu' — a terracotta cooking pot, from the Arabic 'taio' — in which the dish is built in layers: pasta, a sauce of slow-cooked lamb and beef shredded by hand, fried aubergine and grated pecorino, traditionally finished over coals. It's Cefalù's identity dish, cooked in homes for the feast of the Santissimo Salvatore in the first week of August, when the town also holds a sagra dedicated to it — if you're in residence then, that's the night to eat it in company. The rest of the year, look for it on the menus of traditional trattorias in Cefalù's old town (ask specifically — not every tourist menu carries it, and the ones that do tend to be the more serious kitchens). It's rich mountain-meets-sea comfort food, best at a long lunch. Check current openings and reviews before picking a restaurant, or better: ask on the noticeboard which trattoria the ambassadors rate this year.",
    maps_query: "trattoria tradizionale Cefalù centro storico",
    sources: ["https://cefalu.it/magazine/la-tradizione-della-pasta-a-taianu-a-cefalu/", "https://www.visitcefalu.com/event/xiii-sagra-ra-pasta-a-taianu/"],
  },
  {
    name: "Nangalarruni: the mushroom temple of Castelbuono",
    emoji: "🍄",
    category: "food",
    distance: "35 min drive",
    effort: null,
    season: "year-round (mushroom season peaks in autumn)",
    blurb: "The Madonie's most famous table: a Michelin Bib Gourmand institution that has been turning the mountains' wild mushrooms and black pork into pilgrimage-worthy plates since 1984.",
    details: "Peppe Carollo's Nangalarruni — named after the Sicilian word for a Jew's harp — occupies a cosy old room in Castelbuono's centre and has spent four decades perfecting cucina delle Madonie: wild mushrooms from the park's woods (the autumn funghi di bosco menus are the stuff of legend), suino nero — the semi-wild Madonie black pig — smoked, roasted and cured, mountain cheeses, and a cellar said to hold over 600 labels. It carries a Michelin Bib Gourmand for quality at honest prices, and the dining room is small, so booking ahead is close to mandatory year-round. It's the natural grand finale to a Castelbuono day: castle and manna shopping first, then a long lunch or early dinner here. If mushrooms aren't your family's thing, the menu covers the rest of the mountain larder generously. As always, check current opening days before driving up.",
    maps_query: "Ristorante Nangalarruni Castelbuono",
    sources: ["https://guide.michelin.com/en/sicilia/castelbuono/restaurant/nangalarruni", "https://cefalu.it/en/magazine-en/experience-en/nangalarruni/"],
  },
  {
    name: "Granita & brioche mornings",
    emoji: "🍧",
    category: "food",
    distance: "25 min drive (any good Cefalù bar)",
    effort: null,
    season: "summer (though bars serve it well into autumn)",
    blurb: "The Sicilian summer breakfast: a glass of impossibly smooth lemon or almond granita, a warm brioche col tuppo to tear and dunk, and nowhere to be until the beach.",
    details: "Granita in Sicily is not a slushie — it's a dense, silky semi-frozen cream of fruit or nuts, churned slowly, and eating it with a soft egg-rich brioche 'col tuppo' (named for its topknot) is the island's canonical summer breakfast. The classics to work through: limone (sharpest and most traditional), mandorla (almond — creamy and perfumed), gelsi neri (black mulberry, in season mid-late summer), caffè with a cap of unsweetened cream, and pistacchio. Any serious bar-pasticceria in Cefalù or Castelbuono will do the ritual properly — the sign of quality is granita that holds its texture without ice crystals and brioche baked that morning. Sit-down at a bar table, order one granita and one brioche per person, and dunk without shame; locals have theirs before 10am, beating both the heat and the queue. Each family will develop a loyal bar within a week — post yours to the Ambassador tips so the village consensus can form.",
    maps_query: "granita e brioche Cefalù",
    sources: ["https://en.wikipedia.org/wiki/Granita"],
  },
  {
    name: "The Madonie tasting board: provola, black pig & mountain cheese",
    emoji: "🧀",
    category: "food",
    distance: "Cefalù & Castelbuono delis, 25-35 min",
    effort: null,
    season: "year-round",
    blurb: "Build the ultimate terrace aperitivo from the mountains around you: Slow Food-protected provola, salumi from semi-wild black pigs, and pecorino from high pastures.",
    details: "The Madonie feed their villages first, and the delis (salumerie/alimentari) of Castelbuono and Cefalù are where to raid the larder. Top of the list is provola delle Madonie — a Slow Food Presidium pear-shaped cow's-milk cheese from the park's semi-wild herds, sold young and mild or aged and sharp; ask for a middle-aged wedge and eat it with local honey. Add salame and cured cuts of suino nero dei Nebrodi/Madonie (the black pig you'll see rooting in the oak woods), sheep's ricotta if you're eating it that day, aged pecorino, olives, and a jar of manna products for the sweet-toothed. Any good deli will vacuum-pack for the flight home. Saturday is the liveliest shopping morning; ask the counter what's from 'qui vicino' — the answer usually comes with a story and a taste. Assemble it all on a Gratteri terrace at sunset with an Etna Rosso and you've matched any restaurant in the province.",
    maps_query: "salumeria Castelbuono",
    sources: ["https://www.fondazioneslowfood.com/en/slow-food-presidia/madonie-provola/"],
  },
  {
    name: "Mountain pastries: lo sfoglio & testa di turco",
    emoji: "🥧",
    category: "food",
    distance: "35-50 min (Castelbuono & Polizzi Generosa)",
    effort: null,
    season: "year-round",
    blurb: "Two pastries you can only really eat here: Polizzi's warm cheese-and-cinnamon pie, and Castelbuono's cloud of custard and crackling pastry named after a Turk's turban.",
    details: "Lo sfoglio (or sfoglio polizzano) is the pride of Polizzi Generosa: a double-crusted pie filled with fresh tuma cheese, sugar, cinnamon and chocolate — a medieval-sounding combination that works completely, best slightly warm from a village pasticceria. Castelbuono answers with testa di turco, layers of paper-thin fried pastry and thick milk-and-cinnamon custard said to be shaped like a turban, eaten cold with a spoon and dusted with cinnamon. Both are village-specific — you won't find them in Palermo — which makes them perfect excuses for a mountain drive with a pastry-box finale. Pair either with the village passeggiata: sfoglio after the Abies nebrodensis trail, testa di turco after the Ventimiglia castle. Ask the pasticceria which morning they bake — small batches sell out on Sundays. And of course there's always cannoli everywhere, filled to order so the shell stays crisp: the only rule is never buy one pre-filled.",
    maps_query: "pasticceria Polizzi Generosa sfoglio",
    sources: ["https://visitpolizzigenerosa.it/it/itinerari/sentiero-abies-nebrodensis-zona-a-del-parco-delle-madonie/", "https://www.visitsicily.info/en/castelbuono-in-the-madonie-mountains/"],
  },
  {
    name: "The agriturismo long lunch",
    emoji: "🫒",
    category: "food",
    distance: "20-40 min drive (farms around Castelbuono & the hills)",
    effort: null,
    season: "year-round (book Sunday lunch ahead)",
    blurb: "Sicily's best-value feast: a working farm, a fixed menu of everything they grew or raised, and three hours you'll defend as the highlight of the trip.",
    details: "Agriturismi — working farms licensed to serve their own produce — dot the hills between Gratteri, Castelbuono and the park, and the format is gloriously fixed: you sit down, plates start arriving (antipasti of their cheeses, salumi, vegetables sott'olio; homemade pasta; grilled meats; dessert; often their own wine and olive oil), and you stop when you surrender. Around Castelbuono, long-established estates such as Bergi — known also for its olive oil — are the classic example; ask ambassadors and locals which farms are currently open for lunch, as arrangements change season to season, and always book a day or two ahead (Sunday lunch is a Sicilian institution and fills up with local families). It's the most kid-friendly eating format in Sicily: space to run, animals to inspect, nobody rushing. Many farms also sell their oil, jams and cheese at the gate — bring cash and boot space. Expect to need no dinner.",
    maps_query: "agriturismo Castelbuono",
    sources: ["https://www.visitsicily.info/en/castelbuono-in-the-madonie-mountains/"],
  },
  {
    name: "Castelbuono food trail: Fiasconaro, manna & Madonie cheese",
    emoji: "🧁",
    category: "food",
    distance: "about 35-40 min drive",
    effort: "easy",
    season: "year-round (manna harvest July-Sept)",
    blurb: "The Madonie's gourmet capital: the pasticceria that made Castelbuono's panettone world-famous, tree sap harvested like nowhere else in Europe, and a castle thrown in.",
    details: "Start in Piazza Margherita at Fiasconaro, the family pasticceria founded in 1953 whose naturally-leavened panettone and colomba are now exported worldwide — sit down for cannoli, cassata, sfince with ricotta and a gelato, and buy an 'Oro di Manna' panettone to take home. Manna is the local marvel: the crystallised sap of manna ash trees, tapped only between Castelbuono and Pollina in late summer, forming white 'cannoli' stalactites on threads — look for manna sweets and spreads in town shops. Hunt out provola delle Madonie, a Slow Food Presidium flask-shaped cow's-milk cheese from semi-wild mountain herds, in local delis and on trattoria boards. Then visit the 1317 Ventimiglia castle and the Matrice Vecchia to walk it all off. In Cefalù itself, locals rate the family-run pasticcerias near the station for cannoli — ask an ambassador for their favourite and add it to the tips!",
    maps_query: "Pasticceria Fiasconaro Castelbuono",
    sources: ["https://fiasconaro.com/en/manna-our-treasure/", "https://www.fondazioneslowfood.com/en/slow-food-presidia/madonie-provola/"],
  },

  {
    name: "Dinner on the Cefalù waterfront",
    emoji: "🦑",
    category: "food",
    distance: "25 min drive",
    effort: null,
    season: "year-round (terraces best May-Oct)",
    blurb: "The classic Cefalù evening: fresh-off-the-boat seafood at a table almost in the sea, with the old town glowing behind you.",
    details: "Cefalù's old town is thick with seafood restaurants; a few long-standing names to start from (always check current openings and reviews, and book in summer): Al Porticciolo down by the old port, with a terrace on the cliff over the water; La Botte, a decades-old family institution near the cathedral doing creative Sicilian cooking; and Locanda del Marinaio, an unpretentious spot that's earned serious recognition. Order what's local and seasonal — swordfish (pesce spada), red prawns (gamberi rossi di Mazara), sea urchin or cuttlefish-ink pasta, and whatever the day's catch is. Aim for a table booked at sunset so the meal starts with the light on the rooftops. This is the one splurge dinner most families do at least once a stay. Which of these is best this year is exactly what the ambassadors' votes and tips are for — thumbs them up and add your own find.",
    maps_query: "seafood restaurant Cefalù old town",
    sources: ["https://www.tripadvisor.com/Restaurants-g194726-c33-Cefalu_Province_of_Palermo_Sicily.html", "https://www.alporticcioloristorante.com/en-gb/the-restaurant"],
  },
  {
    name: "Aperitivo & the evening passeggiata",
    emoji: "🍹",
    category: "food",
    distance: "in town, or Cefalù 25 min",
    effort: null,
    season: "year-round (liveliest in summer)",
    blurb: "The most Sicilian thing you'll do all trip costs the price of a spritz: dress up a little, drift through the lanes at dusk, and watch the whole village do the same.",
    details: "As the heat lifts, Sicilian towns come out to walk — the passeggiata — and the ritual pairs perfectly with an aperitivo. In Gratteri, that's a drink in the piazza as the swifts wheel overhead; in Cefalù, a table on Corso Ruggero or by the sea with a Spritz, a glass of local white, or a Sicilian classic like Amaro Averna (made just inland at Caltanissetta) over ice. Aperitivi usually come with olives, crisps, and little bites. Go around 7-8pm, let the kids run in the square, and treat it as the warm-up to a late Sicilian dinner. It costs almost nothing and is the fastest way to feel like a local rather than a tourist. Bonus: it's the natural moment to bump into other ambassadors who are in town — check the calendar first.",
    maps_query: "Corso Ruggero Cefalù",
    sources: ["https://en.wikipedia.org/wiki/Passeggiata"],
  },

  // ---------- Wine & vineyards ----------
  {
    name: "The wines of the Madonie & Contea di Sclafani",
    emoji: "🍇",
    category: "wine",
    distance: "the hills around you",
    effort: null,
    season: "year-round",
    blurb: "A quick field guide to what's in the glass here — so you can shop and order like you know the region, because you now do.",
    details: "Your corner of Sicily sits inside the Contea di Sclafani DOC, a large appellation spanning the inland hills around the Madonie. Reds lean on Nero d'Avola (rich, dark-fruited, the island's signature) and the more local, structured Perricone; whites on Catarratto, Inzolia and Grillo — bright, citrusy, made for seafood. Higher-altitude Madonie vineyards give fresher, more elegant wines than the Sicilian stereotype of big and jammy. For a splurge, look for Etna wines (Nerello Mascalese reds, Carricante whites) from the volcano further east, increasingly on local lists. When ordering, 'un rosso del posto' or 'un bianco locale' will get you something honest and inexpensive; in shops, ask for Contea di Sclafani or Sicilia DOC bottles. Two nearby estates below are worth a proper visit.",
    maps_query: "Contea di Sclafani wine region",
    sources: ["https://en.wikipedia.org/wiki/Contea_di_Sclafani_DOC", "https://en.wikipedia.org/wiki/Sicilian_wine"],
  },
  {
    name: "Tasca d'Almerita — Tenuta Regaleali",
    emoji: "🍷",
    category: "wine",
    distance: "about 1h15 drive (Sclafani Bagni)",
    effort: null,
    season: "year-round (book ahead; harvest Aug-Oct)",
    blurb: "One of Sicily's most storied wine estates, on the inland edge of your own DOC — vineyard tours, tastings, a cooking school, and long lunches among the hills.",
    details: "The Tasca d'Almerita family has made wine at Tenuta Regaleali near Sclafani Bagni since 1830, on a vast estate in the rolling hills south of the Madonie — the heart of the Contea di Sclafani. It's the birthplace of benchmark Sicilian wines like the Rosso del Conte, and the estate is famous well beyond wine: its historic cooking school (associated with the late Anna Tasca Lanza) helped put Sicilian home cooking on the world map. Visits typically combine a vineyard and cellar tour with a seated tasting, and can extend to a full lunch of estate produce — book well ahead through the estate. It's a longer drive than the nearer wineries but a genuine bucket-list Sicilian wine day for interested parents (arrange it as a grown-ups' outing). Pair the route with a stop in one of the inland borghi. Always confirm visit options and times directly before setting out.",
    maps_query: "Tenuta Regaleali Tasca d'Almerita Sclafani Bagni",
    sources: ["https://en.wikipedia.org/wiki/Tasca_d%27Almerita", "https://www.tascadalmerita.it/en/tenute/regaleali/"],
  },
  {
    name: "Abbazia Santa Anastasia — vineyard & tasting",
    emoji: "🍷",
    category: "wine",
    distance: "about 30 min drive",
    effort: null,
    season: "year-round (book ahead; harvest Sept-Oct)",
    blurb: "A 12th-century Benedictine abbey turned biodynamic wine estate in the hills near Castelbuono — the closest serious winery to Gratteri, with vineyard walks and tasting lunches over the sea.",
    details: "On the slopes above the coast near Castelbuono, this ~400-hectare estate has around 65 hectares of vines between 200 and 500 m, and traces its winemaking back to Benedictine monks in the 1100s. It farms organically and biodynamically (Demeter-certified) — flagship reds like Litra sit alongside local varieties such as Nero d'Avola — and runs guided visits with vineyard walks, an explanation of biodynamics, and sommelier-led tastings, often paired with a light Sicilian lunch. There's a relais on site (hotel, pool, restaurant) if the parents fancy a treat night. Being only about half an hour away, it's the easiest winery half-day from Gratteri. Book tastings in advance by email or a wine-tourism platform rather than turning up; harvest-season visits are especially atmospheric.",
    maps_query: "Abbazia Santa Anastasia winery Castelbuono",
    sources: ["https://www.abbaziasantanastasia.com/en/", "https://www.winerytastingsicily.com/producer/abbazia-santa-anastasia-castelbuono-palermo-cefalu/"],
  },

  // ---------- Day trips ----------
  {
    name: "Cefalù old town & Arab-Norman Duomo",
    emoji: "⛪",
    category: "daytrip",
    distance: "25 min drive",
    effort: "easy",
    season: "year-round",
    blurb: "Your 'local' town is a UNESCO World Heritage showstopper: a Norman cathedral with the finest Byzantine Christ Pantocrator mosaic in Italy, wrapped in a fishing-village old town.",
    details: "The Duomo was begun in 1131 after King Roger II survived a storm at sea, and Byzantine masters from Constantinople finished the apse mosaics before 1170 — the Pantocrator holds a gospel reading 'I am the light of the world' in Greek and Latin. It is part of the UNESCO Arab-Norman Palermo/Cefalù/Monreale site, and its pilaster decoration echoes Gratteri's own San Giorgio abbey, built in the same years. Afterwards wander Corso Ruggero and the lanes down to the sea: find the Lavatoio Medievale, a sunken medieval-origin washhouse where the Cefalino river gushes from 22 cast-iron spouts (free, reached by a polished lava-stone staircase), and Porta Pescara, the only surviving medieval sea gate, whose Gothic arch frames the fishing boats — the classic photo. Go early morning or late afternoon in summer; shoulders and knees covered inside the cathedral. Combine with a swim off the old-town beach and dinner on the harbour wall.",
    maps_query: "Duomo di Cefalù",
    sources: ["https://whc.unesco.org/en/list/1487/", "https://cefalu.it/en/magazine-en/the-medieval-wash-house-of-cefalu/"],
  },
  {
    name: "La Rocca climb & Temple of Diana",
    emoji: "🥾",
    category: "daytrip",
    distance: "25 min drive + 45-60 min climb",
    effort: "challenging",
    season: "year-round (avoid midday in summer)",
    blurb: "The great crag looming over Cefalù hides a megalithic temple, a Norman-era castle and a 360° panorama over the red rooftops, the Duomo and the Tyrrhenian.",
    details: "The path (Salita Saraceni) starts near Corso Ruggero and zigzags up through three tiers of old city walls; allow 30-45 minutes to the top and 1.5-2 hours total. Halfway up sits the so-called Temple of Diana, a megalithic structure said to date to the 9th-8th century BC, and the summit holds the ruins of a 13th-century castle with sweeping views of town, coast and the Madonie. There is almost no shade, so start before 9:30 in summer and carry at least a litre of water each; proper shoes beat sandals on the loose gravel sections. There is a small entry fee to the archaeological park (check locally for hours). Great with older kids; not buggy-friendly. Sunset light on the bay is spectacular but check closing times before planning an evening climb.",
    maps_query: "La Rocca di Cefalù Salita Saraceni",
    sources: ["https://www.visitcefalu.com/en/rocca-di-cefalu/", "https://www.alltrails.com/trail/italy/sicily/la-rocca-cefalu"],
  },
  {
    name: "Himera: Temple of Victory & Antiquarium",
    emoji: "🏛️",
    category: "daytrip",
    distance: "about 30 min drive",
    effort: "easy",
    season: "year-round (spring and autumn are loveliest)",
    blurb: "Stand where Greeks crushed a Carthaginian invasion in 480 BC — archaeologists found the soldiers' mass graves here, and the temple built to celebrate the victory still stands in a field by the sea.",
    details: "Himera was a Greek colony founded in 648 BC at the mouth of the Imera river, just west of Campofelice — you pass it on the way to Palermo. The Doric Temple of Victory (c. 480-470 BC) is traditionally linked to the great Battle of Himera of 480 BC, when a Greek coalition under Gelon of Syracuse defeated Carthage; recent excavations of the western necropolis uncovered mass graves of warriors from the battles of 480 and 409 BC. The upper town preserves the sanctuary of Athena and street grid, and the Antiquarium 'Pirro Marconi' museum displays finds including a cast of a mass-grave skeleton, a horse skull with bronze bit, and weapons bent by battle impact — genuinely gripping for kids. The site is rarely busy, so you often have it nearly to yourself. Little shade in summer: hats and water. Check locally for current opening days before driving over.",
    maps_query: "Parco Archeologico di Himera Antiquarium",
    sources: ["https://en.wikipedia.org/wiki/Temple_of_Victory_(Himera)", "https://www.italia.it/en/sicilia/termini-imerese/cultural-places/himera-archaeological-area"],
  },
  {
    name: "Caccamo Castle",
    emoji: "🏰",
    category: "daytrip",
    distance: "about 50 min drive",
    effort: "easy",
    season: "year-round",
    blurb: "One of the largest and best-preserved Norman castles in Sicily — a white-stone fortress on a cliff, complete with battlements, a conspiracy hall and a weapons museum.",
    details: "Castello di Caccamo crowns a crag 521 m up, overlooking the San Leonardo valley and the Rosmarina lake, and is counted among the biggest castles in Italy. Its core was built in the 12th century by Matteo Bonello and extended by the Chiaramonte family in the 14th; the famous Sala della Congiura is where Norman barons plotted their failed 1160 revolt against King William I. Inside is a maze of rooms, stairways and ramparts with V-shaped battlements, plus a museum of ancient weapons that lands well with children. A restaurant occupies the old stables at ground level, and the town below has fine churches around the Chiesa Madre. It's an easy half-day, best combined with Himera or Termini Imerese on the way; check locally for opening days and guided-visit times.",
    maps_query: "Castello di Caccamo",
    sources: ["https://en.wikipedia.org/wiki/Castello_di_Caccamo", "https://www.visitsicily.info/en/castle-of-caccamo/"],
  },
  {
    name: "Palermo: Cappella Palatina, markets & street food",
    emoji: "🍋",
    category: "daytrip",
    distance: "1h15 drive (or train from Cefalù)",
    effort: "moderate",
    season: "year-round (spring/autumn ideal; hot in August)",
    blurb: "Sicily's chaotic, glorious capital: a golden Byzantine chapel built for a Norman king, then souk-like markets where lunch is fried chickpea fritters eaten standing up.",
    details: "Do the Palazzo dei Normanni first thing: the Cappella Palatina, commissioned by Roger II in 1132, fuses Byzantine gold mosaics, Arab muqarnas ceilings and Norman architecture — book timed tickets in advance as slots sell out on peak dates. Then dive into the markets: Ballarò is the oldest and most raucous, Capo slightly calmer with excellent street food. Eat as Palermitans do: pane e panelle (chickpea fritter sandwich), arancine, sfincione (spongy onion-and-tomato Sicilian pizza), and for the brave, stigghiola from a smoking grill. Fit in the Quattro Canti, the cathedral and Teatro Massimo facade on a walking loop. Consider the train from Cefalù (roughly an hour) to skip city parking entirely — Palermo driving is not for the faint-hearted. Keep valuables zipped in the market crush, and go on a weekday morning for the full show.",
    maps_query: "Cappella Palatina Palazzo dei Normanni Palermo",
    sources: ["https://www.lonelyplanet.com/articles/top-things-to-do-in-palermo-sicily", "https://whc.unesco.org/en/list/1487/"],
  },
  {
    name: "Monreale cathedral & cloister",
    emoji: "✨",
    category: "daytrip",
    distance: "about 1h30 drive (just beyond Palermo)",
    effort: "easy",
    season: "year-round",
    blurb: "Around 6,000 square metres of gold mosaics telling the whole Bible in pictures — the grand finale of the same UNESCO Arab-Norman trio as your local Cefalù Duomo.",
    details: "William II's cathedral above Palermo is carpeted in some of the most extensive Byzantine-style mosaics in existence, crowned by a colossal apse Pantocrator whose outstretched arms seem to embrace the nave — compare it with Cefalù's and let the kids vote. Don't skip the Benedictine cloister: 228 paired columns, each capital carved differently with beasts, saints and patterns; it's a separate ticket from the cathedral. Climbing to the roof terraces earns views over the Conca d'Oro valley to Palermo and a look down into the cloister. Go early on a weekday and avoid Sunday mornings; shoulders and knees must be covered (carry a scarf in summer). Easiest done as the morning half of a Palermo day — park in Monreale or take the city bus up from Palermo — with mosaics before the crowds, then markets for lunch.",
    maps_query: "Duomo di Monreale",
    sources: ["https://en.wikipedia.org/wiki/Monreale_Cathedral", "https://wearepalermo.com/news/visit-cathedral-of-monreale/"],
  },
];

/* ---------- Local directory: restaurants, cafés & food shops ----------
   Real, web-documented businesses (researched July 2026). Descriptions
   reflect what sources say; hours/quality change, so check ahead — and
   the ambassadors' 👍/👎 votes are the living rating. */
(function () {
  const KIND = {
    restaurant: "🍽️", trattoria: "🍝", seafood: "🦑", pizzeria: "🍕",
    "fine dining": "⭐", cafe: "☕", bar: "🍸", agriturismo: "🚜",
    gelateria: "🍨", pasticceria: "🧁", bakery: "🥖", butcher: "🥩",
    deli: "🧀", producer: "🫙", market: "🧺",
  };
  const DIST = {
    "Gratteri": "in Gratteri", "Cefalù": "Cefalù · 25 min",
    "Sant'Ambrogio": "Sant'Ambrogio · 30 min", "Castelbuono": "Castelbuono · 35 min",
    "Isnello": "Isnello · 15 min", "Collesano": "Collesano · 20 min",
    "Pollina": "Pollina · 35 min", "Gibilmanna": "Gibilmanna · 15 min",
    "Campofelice di Roccella": "Campofelice · 20 min", "Lascari": "Lascari · 20 min",
    "Cerda": "Cerda · 30 min",
  };
  const EAT = [
    ["Cortile Pepe", "fine dining", "Cefalù", "Fine dining steps from the Duomo, in the Michelin Guide — modern land-and-sea Sicilian tasting menus and a ~400-label wine list.", "Cortile Pepe Cefalù", "https://guide.michelin.com/us/en/sicilia/cefal/restaurant/cortile-pepe"],
    ["Qualia", "fine dining", "Cefalù", "Michelin Guide restaurant with exposed brick and a little alfresco space — contemporary Sicilian with fresh fish, Mazara prawn tartare, barbecued octopus.", "Qualia ristorante Cefalù", "https://guide.michelin.com/us/en/sicilia/cefal/restaurant/qualia"],
    ["Le Chat Noir", "restaurant", "Cefalù", "Family-run (the Natoli family) in a late-1500s building near the cathedral — traditional Sicilian cooking with local zero-km produce.", "Ristorante Le Chat Noir Cefalù", "https://ristorantelechatnoir.it/en/le-chat-noir-2/"],
    ["La Botte di Fiduccia", "trattoria", "Cefalù", "Long-established family trattoria near the cathedral under chef Giuseppe Fiduccia — cuttlefish-ink couscous, seafood risotto, whitewashed stone room.", "Trattoria La Botte Cefalù", "https://www.cefalu.website/en/restaurants/la-botte/itm/187/"],
    ["Camilleri", "trattoria", "Cefalù", "Historic-centre trattoria — tuna carpaccio with almond and orange, grilled sea bream, taglioline with sardines, local wines.", "Camilleri Ristorante Trattoria Cefalù", "https://www.tripadvisor.com/Restaurant_Review-g194726-d17630379-Reviews-Camilleri_Ristorante_Trattoria_Cefalu-Cefalu_Province_of_Palermo_Sicily.html"],
    ["Il Carretto", "trattoria", "Cefalù", "Quiet side-street trattoria with vaulted brick ceilings — Sicilian classics (pasta alla Norma, spaghetti alle vongole, grilled swordfish) at fair prices; pork-free menu.", "Ristorante Il Carretto Cefalù", "https://www.tripadvisor.com/Restaurant_Review-g194726-d4766156-Reviews-Il_Carretto-Cefalu_Province_of_Palermo_Sicily.html"],
    ["Al Porticciolo", "seafood", "Cefalù", "Seafood and pizza by the old port with a terrace on the cliff over the sea — molluscs, crustaceans, couscous and wood-fired pizza.", "Al Porticciolo Cefalù", "https://www.alporticcioloristorante.com/en-gb/the-restaurant"],
    ["Lo Scoglio Ubriaco", "seafood", "Cefalù", "On the rocks at the edge of the old town, 30+ years — house tagliatelle in mussel-cream sauce, farfalle with bottarga, sea-view terrace above the port.", "Lo Scoglio Ubriaco Cefalù", "https://www.frommers.com/destinations/cefalu/restaurants/lo-scoglio-ubriaco/"],
    ["Il Covo del Pirata", "seafood", "Cefalù", "Seafront spot with a terrace over the beach and port — paccheri with tuna, spaghetti alle vongole, mixed grilled fish.", "Il Covo del Pirata Cefalù", "https://www.tripadvisor.com/Restaurant_Review-g194726-d1979302-Reviews-Il_Covo_del_Pirata-Cefalu_Province_of_Palermo_Sicily.html"],
    ["Sutt'a Ràvia", "seafood", "Cefalù", "Blue-and-white trattoria metres from the beach, an offshoot of the neighbouring fish market — very fresh fish, caponata, spaghetti alle vongole.", "Sutt'a Ravia Cefalù", "https://www.lonelyplanet.com/italy/sicily/cefalu/restaurants/sutt-a-ravia/a/poi-eat/1623928/360016"],
    ["Ostaria del Duomo", "restaurant", "Cefalù", "Open since 1979 at the foot of the Norman cathedral with a covered terrace on Piazza Duomo — seafood, homemade pistachio pasta, Sicilian desserts.", "Ostaria del Duomo Cefalù", "https://www.tripadvisor.com/Restaurant_Review-g194726-d2318455-Reviews-Ostaria_del_Duomo-Cefalu_Province_of_Palermo_Sicily.html"],
    ["Kentia al Trappitu", "restaurant", "Cefalù", "Clifftop terrace with sunset sea views — fritto misto, pasta alla Norma, pistachio pasta, and a big Sicilian wine list.", "Ristorante Kentia al Trappitu Cefalù", "https://www.tripadvisor.com/Restaurant_Review-g194726-d1576200-Reviews-Ristorante_Kentia_al_Trappitu-Cefalu_Province_of_Palermo_Sicily.html"],
    ["Enoteca Le Petit Tonneau", "cafe", "Cefalù", "Tiny old-town wine bar near the medieval wash-house with three terrace tables famed for sunset over the marina — local wines, cold cuts, sfincione. Book ahead.", "Enoteca Le Petit Tonneau Cefalù", "https://cefalu.it/en/magazine-en/experience-en/le-petit-tonneau-a-glimpse-of-the-world/"],
    ["Bar Duomo — Serio 1952", "cafe", "Cefalù", "Historic café on Piazza Duomo facing the cathedral (since 1952) — cassata, cannoli, frutta martorana, gelato and granita con brioche.", "Bar Duomo Piazza Duomo Cefalù", "https://www.duomo1952.com/"],
    ["Pizzeria White Horse", "pizzeria", "Cefalù", "Popular pizzeria known for thin-crust pizzas and attentive service; bruschette and desserts also singled out by diners.", "Pizzeria White Horse Cefalù", "https://www.tripadvisor.com/Restaurant_Review-g194726-d3814982-Reviews-Pizzeria_White_Horse-Cefalu_Province_of_Palermo_Sicily.html"],
    ["Trattoria Sant'Ambrogio", "trattoria", "Sant'Ambrogio", "Small family trattoria in the fishing hamlet a few km from Cefalù, terrace over the sea — mostly local catch, red-prawn tartare with buffalo mozzarella. Book ahead.", "Trattoria Sant'Ambrogio Cefalù", "https://www.tripadvisor.com/Restaurant_Review-g194726-d15128502-Reviews-Trattoria_Sant_Ambrogio-Cefalu_Province_of_Palermo_Sicily.html"],
    ["Ristorante Dimora dei Frati", "restaurant", "Gratteri", "Family-run in the village core with a terrace and bar, rooted in Sicilian tradition.", "Dimora dei Frati Gratteri", "https://www.visitgratteri.com/it/ristorante-dimora-dei-frati/"],
    ["Al Casato dei Ventimiglia", "pizzeria", "Gratteri", "Village restaurant-pizzeria, a local reference point for meat, fish, pizza and Sicilian specialities.", "Al Casato dei Ventimiglia Gratteri", "https://www.tripadvisor.com/Restaurants-g1463398-c26-Gratteri_Province_of_Palermo_Sicily.html"],
    ["La Villa", "restaurant", "Gratteri", "Casual spot for pizza and pasta with outdoor seating, well liked for value.", "La Villa Gratteri", "https://www.tripadvisor.com/Restaurant_Review-g1463398-d2531060-Reviews-La_Villa-Gratteri_Province_of_Palermo_Sicily.html"],
    ["Gratteri Resort restaurant", "restaurant", "Gratteri", "Hotel restaurant of Mediterranean cuisine — Madonie tradition with new touches and a broad Madonie/Sicilian wine list.", "Gratteri Resort restaurant", "https://www.gratteriresort.com/en/our-restaurant/"],
    ["Case Risino", "agriturismo", "Gratteri", "Hilltop countryside agriturismo in the Rapputi area with sea views toward Lascari, cooking seasonal local produce.", "Case Risino Gratteri", "https://www.caserisino.it/"],
    ["Sesto 6 Senso", "restaurant", "Castelbuono", "Restaurant-pizzeria near Fontana Venere Ciprea in the old centre — local and Mediterranean dishes at friendly prices.", "Sesto 6 Senso Castelbuono", "https://ristorantiinsicilia.it/dove-mangiare-a-castelbuono/"],
    ["Trattoria La Lanterna", "trattoria", "Castelbuono", "Cosy trattoria with a fireplace — praised for mixed antipasti, grilled mushrooms and generous pasta.", "Trattoria La Lanterna Castelbuono", "https://wanderlog.com/list/geoCategory/341229/best-italian-restaurants-in-castelbuono"],
    ["U Trappitu", "restaurant", "Castelbuono", "Restaurant-pizzeria in the historic centre — typical Madonie cooking and Mediterranean fish at competitive prices.", "U Trappitu Castelbuono", "https://ristorantiinsicilia.it/dove-mangiare-a-castelbuono/"],
    ["Hostaria Cycas", "restaurant", "Castelbuono", "In an ancient building with a courtyard holding one of the Madonie's oldest cycas — fresh pasta, homemade bread, seasonal mushrooms, local meats, wood-fired pizza.", "Hostaria Cycas Castelbuono", "https://www.hostariacycas.net/"],
    ["Agriturismo A Rametta", "agriturismo", "Castelbuono", "Countryside farm restaurant with abundant dishes from km-0 and own-production ingredients.", "Agriturismo A Rametta Castelbuono", "https://ristorantiinsicilia.it/dove-mangiare-a-castelbuono/"],
    ["Ristorante Pizzeria La Brace", "pizzeria", "Isnello", "Renowned for ancient-grain, 72-hour-fermented pizza plus Madonie cuisine, tasting antipasti and local wines with mountain views.", "La Brace Isnello", "https://www.storienogastronomiche.it/la-brace-isnello-pa-grande-pizza-prelibatezze-delle-madonie/"],
    ["Targa Food", "pizzeria", "Collesano", "Restaurant-pizzeria in the heart of the Madonie and Targa Florio country — Sicilian dishes in a welcoming setting.", "Targa Food Collesano", "https://www.ristorantepizzeriatargafood.it/"],
    ["Trattoria Carricaturi", "trattoria", "Collesano", "Trattoria on Via Mazzini serving typical Madonie cuisine.", "Trattoria Carricaturi Collesano", "https://www.sluurpy.it/collesano/ristorante/172073/trattoria-carricaturi"],
    ["Casale Drinzi", "agriturismo", "Collesano", "Farm restaurant deep in the Madonie park — revisited tradition, quality ingredients, warm service.", "Casale Drinzi Collesano", "https://www.sluurpy.it/collesano/ristorante/28449/casale-drinzi"],
    ["Arrhais", "seafood", "Pollina", "Seafood trattoria at Finale di Pollina with panoramic outdoor seating — linguine with tuna and wild fennel, spaghetti with sea urchin, grilled fish.", "Arrhais Finale di Pollina", "https://www.arrhais.com/wp/"],
    ["La Strummula (Borgo di Ciaùla)", "fine dining", "Pollina", "Restaurant of the Borgo di Ciaùla hotel with chef Santino Corso (ex-Charleston, Mondello) — refined seafood plates.", "La Strummula Borgo di Ciaula Pollina", "https://www.gamberorosso.it/notizie/ristoranti/mangiare-in-sicilia-da-palermo-a-finale-di-pollina/"],
    ["Bastione & Costanza", "restaurant", "Gibilmanna", "Gastro-cultural hub in the former Capuchin infirmary — pizzeria and restaurant focused on local territory and sustainability.", "Bastione Costanza Gibilmanna", "https://www.tripadvisor.com/RestaurantsNear-g194726-d3214960-Santuario_Gibilmanna-Cefalu_Province_of_Palermo_Sicily.html"],
    ["Ristorante Mogavero", "restaurant", "Gibilmanna", "Near the Gibilmanna sanctuary with outdoor seating amid nature — abundant, well-regarded cooking and cordial hospitality.", "Ristorante Mogavero Gibilmanna", "https://restaurantguru.it/Ristorante-Mogavero-di-Gibilmanna-Cefalu"],
    ["Mareluna Village", "restaurant", "Campofelice di Roccella", "Restaurant in a seaside tourist village steps from the sand, cooking Sicilian products and recipes.", "Mareluna Village Campofelice di Roccella", "https://www.thefork.it/ristorante/mareluna-village-r213027"],
    ["Agriturismo Le Campanelle", "agriturismo", "Lascari", "Agriturismo restaurant with pool between Cefalù and Campofelice — Sicilian cooking from fresh farm ingredients, daily-changing menu.", "Agriturismo Le Campanelle Lascari", "https://www.aziendacampanelle.com/"],
  ];
  const SHOP = [
    ["Panificio San Giacomo", "bakery", "Gratteri", "The village bakery on Corso Umberto I, listed in Gratteri's own commercial register.", "Panificio San Giacomo Gratteri", "http://www.comune.gratteri.pa.it/zf/index.php/esercizi-commerciali/"],
    ["Macelleria Occorso", "butcher", "Gratteri", "Village butcher-and-grocery on Corso Umberto in Gratteri, in the municipal business directory.", "Macelleria Occorso Gratteri", "http://www.comune.gratteri.pa.it/zf/index.php/esercizi-commerciali/"],
    ["Gelateria Pasticceria Cangelosi", "pasticceria", "Cefalù", "Family shop on Via Aldo Moro noted for fresh-ricotta cannoli and crisp Sicilian pastries.", "Gelateria Pasticceria Cangelosi Cefalù", "https://gelateria-pasticceria-cangelosi.res-menu.net/"],
    ["Pasticceria Tentazioni", "pasticceria", "Cefalù", "Sea-view bar-pasticceria (Giuseppe Serio) — cannoli filled to order with fine ricotta, hand-decorated cassate.", "Pasticceria Tentazioni Cefalù", "https://www.pasticceriatentazionicefalu.com/"],
    ["Mon Chou-Chou", "gelateria", "Cefalù", "Gelateria-pasticceria on Via Giglio, a Gambero Rosso 'Due Coni' winner using Sicilian raw materials, with gluten-free and vegan options.", "Mon Chou-Chou Cefalù", "https://www.balarm.it/news/cefalu-sul-podio-del-gelato-mon-chou-chou-conquista-i-due-coni-del-gambero-rosso-167709"],
    ["Sapore di Sale", "gelateria", "Cefalù", "Artisan gelateria on Corso Ruggero known for flavours like white chocolate with Nebrodi lemon and sea salt; often a queue.", "Sapore di Sale Gelateria Cefalù", "https://yeasteria.it/sapore-di-sale-gelateria-cefalu/"],
    ["Squagghio", "gelateria", "Cefalù", "Historic-centre gelateria praised for creative combos (pistachio-ricotta) and vegan options.", "Squagghio gelateria Cefalù", "https://wanderlog.com/list/geoCategory/49720/places-to-have-best-gelato-in-cefalu"],
    ["Panificio Purpora", "bakery", "Cefalù", "Small bakery on Corso Ruggero near the Duomo, good for pizza, focaccia and baked goods.", "Panificio Purpora Cefalù", "https://www.tripadvisor.com/Restaurant_Review-g194726-d7161025-Reviews-Panificio_Purpora-Cefalu_Province_of_Palermo_Sicily.html"],
    ["Non Solo Pane", "bakery", "Cefalù", "Artisan bakery-rosticceria on Via Spinuzza — sfincione, arancine and biscuits from quality ingredients.", "Non Solo Pane Cefalù", "https://trovaweb.net/panificio-rosticceria-non-solo-pane-cefalu-palermo/"],
    ["La Cefalù Nostrana", "deli", "Cefalù", "Mini-market and salumeria stocking quality cured meats, artisan cheeses, local wines and regional products.", "La Cefalù Nostrana Cefalù", "https://www.lacefalunostrana.com/"],
    ["Bottega del Sole", "deli", "Cefalù", "Food shop selling bread, typical biscuits and sweets, Sicilian salumi and cheeses alongside local products.", "Bottega del Sole Cefalù", "https://www.facebook.com/people/Bottega-del-Sole-Cefal%C3%B9/100054865454967/"],
    ["Macellerie Cusimano", "butcher", "Castelbuono", "Butcher on Piazza San Francesco — Madonie meats, salumi, cheeses and oil from small local producers.", "Macellerie Cusimano Castelbuono", "https://www.macelleriecusimano.it/"],
    ["Pina Forti — Pane e Biscotti", "bakery", "Castelbuono", "Three-generation bakery-biscottificio on Via Dante — bread, sweets and biscuits made daily in the traditional way.", "Pina Forti Castelbuono", "https://www.pinaforti.it/"],
    ["Antico Forno Prestianni", "bakery", "Castelbuono", "Traditional bakery on Via Umberto I in the town centre.", "Antico Forno Prestianni Castelbuono", "https://www.paginegialle.it/castelbuono-pa/antico-forno-prestianni-g-cira-g"],
    ["Caseificio San Nicola", "producer", "Castelbuono", "Family Madonie dairy making fresh and aged cheeses worked by hand.", "Caseificio San Nicola Castelbuono", "https://www.caseificiosannicola.com/"],
    ["Consorzio Manna Madonita", "producer", "Castelbuono", "Producers of manna — the sweet ash-tree sap still harvested only in Castelbuono and Pollina.", "Consorzio Manna Madonita Castelbuono", "https://www.facebook.com/mannamadonita/"],
    ["Cappadonia Gelati", "gelateria", "Cerda", "Madonie gelateria (lab in Cerda) with territory-driven flavours including Castelbuono manna; multi-year Gambero Rosso 'Tre Coni'.", "Cappadonia Gelati Cerda", "https://www.cappadonia.it/"],
  ];
  const toEntry = (cat) => ([name, kind, town, known, maps, src]) => ({
    name, emoji: KIND[kind] || "🍽️", category: cat, distance: DIST[town] || town,
    effort: null, season: null, blurb: known, details: "", maps_query: maps, sources: [src],
  });
  window.EXPLORE_DATA.push(...EAT.map(toEntry("eat")), ...SHOP.map(toEntry("shop")));
})();
