/* ============================================================
   Gratteri Ambassadors — AI Tour Guide data
   Researched and verified via web sources, July 2026.
   Categories: village | nature | towns | beach | food | daytrip
   ============================================================ */

window.EXPLORE_DATA = [
  // ---------- In & around Gratteri ----------
  {
    name: "Grotta Grattara & the Nymph's Spring",
    emoji: "🧙",
    category: "village",
    distance: "25 min walk uphill (or 5 min drive + short walk)",
    effort: "easy",
    season: "year-round",
    blurb: "The cave that (probably) gave Gratteri its name is the legendary home of 'a Vecchia Strina' — Gratteri's own Befana — and hides a natural stone basin carved by millennia of dripping water.",
    details: "The cave gapes in the cliffs of Pizzo di Pilo just above the village, reached by a winding path from the Piano San Nicola picnic area through a fragrant pine wood, past a rock formation locals call the 'lazzu di voi' (oxen's bed). Inside, a crater-like boulder holds a basin shaped entirely by dripping water, which tradition holds to be purgative and restorative — the 'nymph's spring'. Legend says the old woman of the cave slips down the village chimneys on New Year's Eve to fill children's stockings, a story still celebrated in town. The mouth of the cave doubles as a natural balcony over the rooftops of Gratteri and the Tyrrhenian coast. Wear proper shoes — the final stretch is rocky — and combine it with the San Giorgio loop hike for a half-day outing. The pineta around it is a lovely spot for a picnic with kids.",
    maps_query: "Grotta Grattara, Gratteri",
    sources: ["https://www.visitgratteri.com/en/experience/the-grattaras-cave-park-and-excursions-in-the-pinewood/", "https://cefalu.it/en/things-to-do-en/grotta-grattara-park-discovering-the-fountain-of-the-ninfa/"],
  },
  {
    name: "Abbazia di San Giorgio (Norman abbey ruins)",
    emoji: "🛡️",
    category: "village",
    distance: "30 min walk from town (or short drive + walk)",
    effort: "easy",
    season: "year-round",
    blurb: "A ruined Norman abbey in the woods founded by Roger II around 1140 — the only Premonstratensian house ever built in Sicily, wrapped in Knights of Malta and even Holy Grail legends.",
    details: "Roger II is said to have founded this abbey around 1140 to seal peace with Pope Innocent II, entrusting it to white-robed French Premonstratensian canons; around 1300 it passed to the Knights Hospitaller of Jerusalem (later Knights of Malta), who held it as a commandery for centuries. The surviving walls trace a three-nave basilica with three apses, and its pilaster decoration echoes Cefalù's cathedral, built in the same years. Local lore claims hidden treasure and even the Holy Grail were sought among the ruins by mysterious foreigners — a story your kids will love on the walk out. The classic way to visit is the marked Gratteri loop trail (about 6 km, roughly 300 m of climb, 2-2.5 hours) that links the abbey, the San Giorgio wood and the Grotta Grattara. The Hospitallers' legacy lives on in town too: Via Ospedale is named for their pilgrims' hospital, and the cult of Saint James they brought is still felt. Go late afternoon for golden light on the stones.",
    maps_query: "Abbazia di San Giorgio, Gratteri",
    sources: ["https://www.visitgratteri.com/en/history-of-the-monastery-of-san-giorgio-the-only-house-of-the-premonstratensians-in-sicily/", "https://www.alltrails.com/trail/italy/sicily/gratteri-abbazia-san-giorgio"],
  },
  {
    name: "Gratteri old town: Chiesa Madre, belvedere & medieval lanes",
    emoji: "🏘️",
    category: "village",
    distance: "in town",
    effort: "easy",
    season: "year-round",
    blurb: "A maze of Arab-Norman lanes hiding relics said to come from Jerusalem — including four thorns of Christ's crown — and a belvedere nicknamed 'the balcony on the Tyrrhenian Sea'.",
    details: "Start at the 19th-century Chiesa Madre di San Michele Arcangelo (consecrated 1854), whose Ventimiglia chapel guards relics brought back from the Holy Land: four thorns said to be from the crown of Christ, a fragment of the Cross and a rib-bone relic of Saint James — a legacy of the village's Knights Hospitaller past. From Belvedere Ganci Battaglia the view sweeps over the coast to Cefalù, and on the clearest days you can pick out the Aeolian Islands. Seek out the Fontana della Ninfa, once topped by a nude nymph statue that spouted water from her breasts — the village's pagan 'genius loci'. Along Via Fiume, three medieval bridges and the Fantina well survive from when the Crati stream ran openly through town; it still flows beneath the street, dividing the oldest quarter from the newer one. Wander without a map — the lanes converge naturally on the Chiesa Madre square, and the older Matrice Vecchia is worth a peek if open (check locally).",
    maps_query: "Chiesa Madre San Michele Arcangelo, Gratteri",
    sources: ["https://www.visitgratteri.com/en/experience/chiesa-madre-and-the-treasures-of-jerusalem/", "https://www.visitcefalu.com/en/discovering-the-treasures-of-gratteri-the-most-mysterious-village-in-the-madonie/"],
  },
  {
    name: "Festa della Vecchia (New Year's Eve)",
    emoji: "🎭",
    category: "village",
    distance: "in town",
    effort: null,
    season: "winter (31 December)",
    blurb: "Gratteri's Befana doesn't wait for Epiphany: on New Year's Eve a masked 'Old Woman' rides a donkey through the lanes, handing out sweets and putting the old year on trial.",
    details: "Unique to Gratteri, 'a Vecchia Strina' descends from her home in the Grotta Grattara on the last night of the year rather than on January 6th. A masked figure hidden under a white sheet rides a donkey through the village, escorted by shouting boys, distributing 'turtigliuna' — buccellato-like pastries stuffed with almonds, hazelnuts, walnuts and dried figs. The procession culminates in the 'vanniata', a mock public trial of the year just ended, riffing on village and world events. Folklorists link the figure to the Roman goddess Strenia and ancient rites of gift-exchange and year-renewal, making this one of the most archaic surviving festivals in the Madonie. If your family is at the house over New Year, this is the night to be in the piazza; dress warmly, as Gratteri sits at about 650 m. Dates and format can vary year to year, so check locally or with the comune.",
    maps_query: "Piazza Ungheria, Gratteri",
    sources: ["https://www.visitgratteri.com/en/a-vecchia-end-of-year-event/", "https://www.enjoysicilia.it/en/curiosities/leggenda-vecchia-strina/"],
  },
  {
    name: "Abbazia di Santa Maria del Pedale walk",
    emoji: "🌿",
    category: "village",
    distance: "45-60 min walk from town",
    effort: "moderate",
    season: "spring & autumn",
    blurb: "The quieter sibling of San Giorgio: remains of an abbey founded around 1130 by Byzantine-rite Basilian monks, tucked into green valley country below the village.",
    details: "Said to be one of the oldest monastic foundations in Sicily, Santa Maria del Pedale was established around 1130 by Basilian monks of the Byzantine rite and later passed to the Benedictines — evidence of how many monastic orders converged on tiny Gratteri in the Middle Ages. It features on guided 'roads, knights and medieval monastic orders' walking itineraries that string together the Grotta Grattara, San Giorgio and Pedale along what is believed to be an ancient Roman-era road, so history-minded families can do all three in one epic day. The setting — pasture, oak woods and the Valle del Berillo — is as much the point as the stones. Paths are unevenly marked, so download an offline track (Wikiloc has local routes) or join a local guided excursion via the visitgratteri events pages. Spring brings wildflowers and running springs; autumn gives the best walking temperatures. Combine with a picnic and you've got Gratteri's landscape and its medieval story in a single walk.",
    maps_query: "Santa Maria del Pedale, Gratteri",
    sources: ["https://eventi.visitgratteri.com/en/on-foot/grattara-cave-abbeys-of-san-giorgio-and-santa-maria-del-pedale-discovering-roads-knights-and-medieval-monastic-orders/", "https://www.gratteriholiday.com/en/nature-walks-and-hikes-in-gratteri/"],
  },
  {
    name: "Santuario di Gibilmanna",
    emoji: "⛪",
    category: "village",
    distance: "15 min drive",
    effort: "easy",
    season: "year-round",
    blurb: "Sicily's beloved mountain sanctuary of the Madonna — founded, tradition says, on a monastery built by Pope Gregory the Great, and revived by a Capuchin friar from Gratteri itself.",
    details: "Perched at about 800 m on the wooded slopes of Pizzo Sant'Angelo, Gibilmanna is one of Sicily's great Marian shrines: tradition traces it to one of six monasteries founded by Gregory the Great in the 6th century, and its miraculous Madonna statue is tied to a legend of a storm-wrecked ship and an ox-cart that stopped here of its own accord. There's a proud local connection — the Capuchin convent was founded in 1535 by Father Sebastiano Majo, a native of Gratteri. In 1954 Pius XII declared the Madonna of Gibilmanna patroness of the Cefalù diocese, and the September 8 pilgrimage still draws crowds from across the Madonie. Don't miss the Museo Fra Giammaria in the old convent workshops and stables, ten rooms of Franciscan art gathered from Capuchin houses across the region. The terrace in front of the church is a superb natural balcony over the coast, and the drive back to Gratteri via the panoramic road is a treat in itself.",
    maps_query: "Santuario di Gibilmanna",
    sources: ["https://en.wikipedia.org/wiki/Sanctuary_of_Gibilmanna", "https://www.wondersofsicily.com/gibilmanna.htm"],
  },
  {
    name: "Isnello village & gorge",
    emoji: "🏞️",
    category: "village",
    distance: "15 min drive",
    effort: "easy",
    season: "year-round",
    blurb: "Gratteri's neighbour squeezed into a limestone gorge, with castle ruins on a crag, medieval churches and caves — a perfect slow afternoon wander.",
    details: "Isnello huddles beneath dolomitic cliffs where its stream has cut a dramatic narrow canyon between the castle rock and the wall of Montagna Grotta Grande. Climb to the ruins of the medieval castle on its rocky spur — best at sunset, when the last light turns the walls and gorge red. In the lanes below you'll find the 15th-century Chiesa Madre and the 14th-century Santa Maria Maggiore with its distinctive bell tower, part of the village's Arab-Norman fabric. Cavers know Isnello for the Abisso del Vento, one of Sicily's most important cave systems with white stalactites and flowstone — but note it is strictly for equipped speleologists with guides, not a walk-in attraction. The village is also a trailhead for walks toward Pizzo Dipilo and a marked Gratteri-Isnello path links the two villages on foot. Pair the visit with an evening at the GAL Hassin astronomical park just outside town.",
    maps_query: "Isnello, Sicily",
    sources: ["https://www.enjoysicilia.it/en/cefalu-parco-madonie/isnello/", "https://www.lasiciliainrete.it/en/directory-tangibili/listing/abisso-del-vento/"],
  },
  {
    name: "GAL Hassin astronomical park (Isnello)",
    emoji: "🔭",
    category: "village",
    distance: "15-20 min drive",
    effort: "easy",
    season: "year-round (clear nights; best in summer)",
    blurb: "One of Europe's most advanced public astronomy centres sits in Gratteri's back yard — evening stargazing run by real astrophysicists under some of Italy's darkest skies.",
    details: "Just past neighbouring Isnello, GAL Hassin (opened 2016) is both a working research centre — part of the International Astronomical Union network, with its Wide-field Mufara Telescope station up at 1,865 m ranking among the highest observing stations in Italy — and a superb visitor attraction. The public campus has a planetarium under a 10 m dome, an observation terrace with a retractable roof and a battery of twelve telescopes, plus an open-air 'solar lab' of sundials and a monumental globe. Evening sessions let families view planets, nebulae and the Moon through the big instruments with astronomers on hand; the Madonie's low light pollution makes for genuinely dark skies. Check the programme and book ahead on galhassin.it, as night openings follow a calendar and fill up in summer — and check whether the session runs in English or Italian. Nights are chilly at altitude even in August, so bring layers. The name comes from the Arabic for Isnello, a nod to Sicily's Arab astronomical heritage.",
    maps_query: "GAL Hassin, Isnello",
    sources: ["https://galhassin.it/en/", "https://cefalu.it/en/things-to-do-en/in-isnello-look-up-and-be-amazed-by-the-stars/"],
  },
  {
    name: "Collesano: Targa Florio museum & maiolica",
    emoji: "🏎️",
    category: "village",
    distance: "20 min drive",
    effort: "easy",
    season: "year-round",
    blurb: "The world's oldest sports-car race thundered through these medieval streets from 1906 to 1977 — Collesano keeps the Targa Florio flame alive, alongside a revived hand-painted ceramics tradition.",
    details: "The Museo Targa Florio, founded in 2004 on the main street, is a shrine to the legendary road race run on the public roads of the Madonie: bronze plaques, drivers' helmets, suits, gloves and photographs from the era when Porsche and Ferrari works teams raced past front doors. The town itself was a corner of the Circuito Piccolo delle Madonie, and petrolheads can still drive the old circuit roads toward Campofelice and Cerda — the successor Targa Florio rally uses them to this day. Collesano's other claim is maiolica: a distinctive centuries-old pottery style that died out and is now being revived by artisan workshops, with ceramic plaques dotted around the old town. Climb the monumental staircase to the 16th-century Basilica di San Pietro to see the spectacular painted crucifix of 1555 hanging in the nave. Museum opening can be limited off-season, so check before driving over.",
    maps_query: "Museo Targa Florio, Collesano",
    sources: ["https://www.wondersofsicily.com/collesano.htm", "https://en.wikipedia.org/wiki/Circuito_delle_Madonie"],
  },

  // ---------- Madonie & nature ----------
  {
    name: "Pizzo Sant'Angelo hike",
    emoji: "⛰️",
    category: "nature",
    distance: "15 min drive to Gibilmanna trailhead",
    effort: "moderate",
    season: "year-round (start early in summer)",
    blurb: "Said to be one of the best lookout peaks in northern Sicily — a forested climb from Gibilmanna sanctuary to a summit with the sea on one side and the Madonie giants on the other.",
    details: "The popular route starts near the Gibilmanna sanctuary and climbs about 7.4 km round trip with roughly 230 m of elevation gain — around 2 hours' walking through holm-oak forest and Mediterranean scrub. Though modest in height (around 1,080 m), the peak towers over the Isnello valley and gives a sweeping panorama: the Tyrrhenian coast and Cefalù one way, and the Carbonara, Cervi and Dipilo massifs of the Madonie the other. The final stretch is rocky and pebbly, so sturdy shoes help; poles are handy for the descent. Combine it with a visit to the sanctuary at the trailhead for an easy half-day. In summer go at dawn or late afternoon — the shade cover is good but the summit is exposed. Winter days can be spectacular for visibility toward the Aeolian Islands.",
    maps_query: "Pizzo Sant'Angelo, Madonie",
    sources: ["https://www.summitpost.org/pizzo-sant-angelo/215255", "https://www.komoot.com/guide/502591/hiking-around-parco-delle-madonie"],
  },
  {
    name: "Pizzo Dipilo summit",
    emoji: "🦅",
    category: "nature",
    distance: "trailheads at town edge",
    effort: "challenging",
    season: "spring & autumn",
    blurb: "The bare limestone dome looming 1,385 m above Gratteri — a wild karst summit where kites and vultures once nested, with the whole Tyrrhenian coast at your feet.",
    details: "Pizzo Dipilo (also written 'di Pilo') is the mountain whose flanks hold the Grotta Grattara; its grey dolomitic mass dominates every view from the village. A loop trail circles the summit area starting from Gratteri, mostly on marked paths, while another classic approach comes up from Isnello with a scramble along the south ridge — either way expect rough karst terrain, little shade and a proper mountain day. The reward is one of the finest 360-degree panoramas in the northern Madonie, over the coast, Cefalù's Rocca and the high peaks around Pizzo Carbonara. Historically kites and vultures nested here, and griffon vultures have been reintroduced in the Madonie park, so keep an eye on the thermals. Take plenty of water, and avoid the exposed summit in high summer heat or low cloud. Less confident walkers can hire a local Madonie park guide — worth it for the karst 'craters' and cave lore on the way up.",
    maps_query: "Pizzo Dipilo",
    sources: ["https://www.summitpost.org/pizzo-dipilo/218326", "https://www.visitgratteri.com/en/experience/di-pilo-lace-and-its-craters/"],
  },
  {
    name: "Piano Battaglia",
    emoji: "⛷️",
    category: "nature",
    distance: "50 min drive",
    effort: "easy",
    season: "year-round",
    blurb: "Sicily's improbable little ski station at 1,600 m — snowball fights with a distant view of the sea in winter, cool high-mountain hiking base in summer.",
    details: "Piano Battaglia sits in a glacial-looking bowl between Pizzo Carbonara and Monte Mufara, and is western Sicily's only ski area, with a lift up Monte Mufara (1,865 m) and beginner-to-intermediate pistes such as the roughly 3 km Sparviero run. In snowy spells (typically January–February) Palermitani flood up for skiing, sledging and snowman-building, so arrive early on winter weekends and carry snow chains — they're often mandatory on the mountain roads. In summer it flips into the main trailhead hub of the Madonie, with marked walks in every direction and mountain rifugi serving hearty lunches. The drive from Gratteri via Isnello and Piano Zucchi is a beautiful winding climb in its own right. Check snow conditions and lift status locally before a winter trip, as openings depend entirely on snowfall.",
    maps_query: "Piano Battaglia, Petralia Sottana",
    sources: ["https://www.petraliavisit.it/en/piano-battaglia-winter-sports-and-ski-runs/", "https://www.enjoysicilia.it/en/cefalu-parco-madonie/parco-delle-madonie/piano-battaglia-madonie/"],
  },
  {
    name: "Pizzo Carbonara",
    emoji: "🏔️",
    category: "nature",
    distance: "50 min to trailhead",
    effort: "moderate",
    season: "spring-autumn",
    blurb: "Summit Sicily's second-highest peak (1,979 m) — a half-day walk through a lunar karst landscape with views said to stretch from the Tyrrhenian Sea to Etna.",
    details: "The classic route starts from the parking areas at Piano Battaglia on the SP54 and climbs past Pizzo Scalonazzo through dolines, sinkholes and wind-sculpted beech woods to the broad summit plateau. A reasonably fit walker does the round trip in roughly 2.5–4 hours; no technical skill is needed, but the rocky karst underfoot is uneven and the plateau is famously misty, so navigation gets genuinely hard in cloud. Go on a clear day, download the GPX track (the AllTrails 'Piano Battaglia – Pizzo Carbonara' route is well reviewed), and bring layers — it can be 15 degrees cooler than the coast. Late spring brings wildflowers and grazing cattle; autumn gives the clearest air for spotting Etna on the horizon. There is no water on the route, so carry plenty.",
    maps_query: "Piano Battaglia parking Pizzo Carbonara trailhead",
    sources: ["https://en.wikipedia.org/wiki/Pizzo_Carbonara", "https://www.alltrails.com/trail/italy/sicily/piano-battaglia-pizzo-carbonara"],
  },
  {
    name: "Gole di Tiberio",
    emoji: "🛶",
    category: "nature",
    distance: "45 min drive",
    effort: "moderate",
    season: "summer",
    blurb: "Drift by dinghy through a 400 m limestone slot canyon on the Pollina river — a UNESCO Geopark site with 50 m walls, eels, dragonflies and swimming holes.",
    details: "This hidden gorge, carved through Upper Triassic limestone around 200 million years old, is run as guided small-boat excursions (roughly 2 hours) from May to September, combining the dinghy passage with a walk and swims along the Pollina river; in the cooler months operators switch to rafting and river-trekking descents in wetsuits. Guides point out fossil gastropods in the rock, bee-eaters and grey wagtails, and a boulder passage said to have been used by brigands. The base area has changing rooms, showers, a bar and picnic/barbecue spots, so it works well as a full family day. Book ahead in July–August through the official goleditiberio.com operator, wear water shoes, and bring a dry bag for phones. Kids generally love it — check minimum ages with the operator when booking.",
    maps_query: "Gole di Tiberio, Pollina river",
    sources: ["https://goleditiberio.com/", "https://cefalu.it/en/things-to-do-en/a-rafting-trip-through-the-gorges-of-tiberio/"],
  },
  {
    name: "Zipline Sicilia (San Mauro Castelverde)",
    emoji: "🪂",
    category: "nature",
    distance: "1 hr drive",
    effort: "easy",
    season: "spring-autumn",
    blurb: "Sicily's first giant zipline: a 1,600 m 'angel flight' face-down over a Madonie valley at up to 130 km/h, with the Tyrrhenian Sea on the horizon.",
    details: "From the hilltop village of San Mauro Castelverde you're harnessed horizontally, superman-style, and launched down a single 1.6 km steel cable that drops about 260 m (from 925 m to 669 m altitude), flying up to roughly 170 m above the ground for about a minute and a half. Tandem 'lancio doppio' flights are offered, so parents can fly alongside kids — check current age/weight limits and book via ziplinesicilia.it, especially on summer weekends. The village itself, one of the highest in the Madonie, has an ancient centre and big sea-to-mountain views worth a wander after your flight, and the same area is the gateway to the Gole di Tiberio below. Flights depend on wind, so keep plans flexible and reconfirm on the day. Combine both for one of the best adventure days in northern Sicily.",
    maps_query: "Zipline Sicilia, San Mauro Castelverde",
    sources: ["https://www.ziplinesicilia.it/", "https://www.sicilying.com/en/experiences/nature/Adventure-parks/en-zip-line-Sanmauro-Castelverde-1171"],
  },
  {
    name: "Parco Avventura Madonie",
    emoji: "🌳",
    category: "nature",
    distance: "55 min drive",
    effort: "moderate",
    season: "summer",
    blurb: "Sicily's first high-ropes adventure park — around 80 tree-top games in the mountain woods above Petralia Sottana, from toddler trails to athlete-grade courses.",
    details: "Opened in 2008 at contrada Gorgonero on the road between Petralia Sottana and Piano Battaglia, this was Sicily's original adventure park and remains the benchmark: roughly ten aerial courses of graded difficulty with about 80 bridges, nets, Tarzan swings and ziplines strung between the trees, all done in harness after a safety briefing. Beyond the ropes there's archery, orienteering, guided trekking, mountain-bike routes and even 'suspended tent' overnight stays seven metres up with transparent roofs for stargazing. Courses exist for small children as well as adults, so mixed-age families are well served; wear closed shoes and tie hair back. Summer weekends get busy — call or message ahead (the park operates seasonally, roughly spring to autumn) to confirm opening and reserve. It combines naturally with a Piano Battaglia walk or a Petralia village visit for a full mountain day.",
    maps_query: "Parco Avventura Madonie, Petralia Sottana",
    sources: ["https://www.parcoavventuramadonie.it/", "https://www.parks.it/parco.madonie/indotto_dettaglio.php?id=1032"],
  },

  // ---------- Historic towns ----------
  {
    name: "Castelbuono",
    emoji: "🏰",
    category: "towns",
    distance: "35 min drive",
    effort: "easy",
    season: "year-round",
    blurb: "The lively capital of the Madonie: a 1317 Ventimiglia castle, the pastry empire behind Italy's most coveted panettone, and Europe's last manna harvest.",
    details: "Start at the Castello dei Ventimiglia, built in 1317 by Count Francesco I Ventimiglia, now the civic museum with a famously stucco-encrusted Palatine chapel. Around Piazza Margherita, the Fiasconaro pasticceria (founded 1953) is the pilgrimage stop — their panettone is exported worldwide and even flew to the International Space Station; try anything made with manna, the sweet ash-tree sap that only Castelbuono and neighbouring Pollina still harvest by hand, and pick up manna chunks in the food shops. Don't miss the Museo Naturalistico Minà Palumbo, a wonderfully old-school natural history collection of Madonie flora and fauna assembled by a 19th-century local doctor-naturalist. Every August the town hosts Ypsigrock, Italy's original boutique indie festival, with the main stage set beneath the castle walls — book accommodation far ahead if visiting then. Come hungry: Castelbuono has some of the best restaurants in the mountains.",
    maps_query: "Castello dei Ventimiglia, Castelbuono",
    sources: ["https://fiasconaro.com/en/", "https://www.ypsigrock.it/en/festival/"],
  },
  {
    name: "Pollina",
    emoji: "🎭",
    category: "towns",
    distance: "35 min drive",
    effort: "easy",
    season: "summer",
    blurb: "A tiny eagle's-nest village at 730 m with a Greek-style stone theatre on its summit — sunset concerts between the Madonie peaks and the sea.",
    details: "Pollina's houses cling to a rock high above the Tyrrhenian coast, a short but spectacular drive from Gratteri, with stone-paved lanes leading up past small churches to the remains of a tower and castle at the top. There sits the Teatro Pietra Rosa, an open-air theatre built in 1979 to a design by Venetian architect Antonio Foscari in homage to classical Greek theatres — its backdrop takes in Castelbuono, Geraci and the mountains, and summer evening performances here are magical (check the 'I Classici del Pietra Rosa' season locally). Pollina shares with Castelbuono the distinction of being the only place in the Mediterranean still producing manna from ash trees, and its small Museo della Manna explains the harvest with tastings and products to buy. Go late afternoon, wander, catch the sunset from the theatre terrace, then dine back down the hill. In high summer, pair it with a swim at Finale di Pollina on the coast below.",
    maps_query: "Teatro Pietra Rosa, Pollina",
    sources: ["https://www.enjoysicilia.it/en/cefalu-parco-madonie/pollina/", "https://www.tripadvisor.com/Attraction_Review-g2270442-d10148952-Reviews-Museo_della_Manna-Pollina_Province_of_Palermo_Sicily.html"],
  },
  {
    name: "Geraci Siculo",
    emoji: "🦅",
    category: "towns",
    distance: "55 min drive",
    effort: "easy",
    season: "year-round",
    blurb: "The old Ventimiglia mountain capital with a vertigo-inducing glass walkway jutting over the cliff where a count and his blindfolded horse leapt into legend.",
    details: "Geraci Siculo, one of the 'Borghi più Belli d'Italia', was the medieval seat of the Ventimiglia counts before Castelbuono, and keeps a proper mountain-borgo feel: castle ruins on the crag, narrow winding alleys and churches wedged between houses. Its showpiece is the Salto dei Ventimiglia, a steel-and-glass platform (opened 2014) projecting about three metres over the ravine where, legend says, Count Francesco I Ventimiglia rode his blindfolded horse off the cliff in 1337 rather than be captured by royal troops — the view sweeps east toward Etna. The town is also famous for its water: springs high in the park feed both the public fountains and the bottled 'Acqua Geraci' brand, so fill your bottles like the locals do. Note the 'salto' here is a viewpoint, not a zipline — the big zipline is at San Mauro Castelverde. It slots perfectly into a day loop with Castelbuono (20 minutes north) or Gangi (further along the SS286/SS120).",
    maps_query: "Salto dei Ventimiglia, Geraci Siculo",
    sources: ["https://visitgeracisiculo.it/il-salto-dei-ventimiglia/", "https://www.acquageraci.it/"],
  },
  {
    name: "Petralia Soprana & the salt mine",
    emoji: "🧂",
    category: "towns",
    distance: "1 hr drive",
    effort: "easy",
    season: "year-round",
    blurb: "Italy's 'most beautiful village' of 2018 at 1,100 m — with a working rock-salt mine beneath it hiding a contemporary art museum carved in salt.",
    details: "Petralia Soprana won RAI's 'Borgo dei Borghi' title in 2018 and earns it: stone lanes, baroque churches with Serpotta stuccos, and three belvederes (Loreto, Carmine and Piazza Duomo) looking out to Etna and half of inland Sicily. Below the village at Raffo, the Italkali mine works a vast deposit of pure rock salt — over 80 km of tunnels — left when the Mediterranean dried out around six million years ago. Inside a disused gallery is MACSS, the 'Museo Sotto Sale', a genuinely unique museum of about forty salt sculptures created during art biennials since 2011; guided visits include helmets and a waiver since it's an active mine. Visits run on limited days and booking is mandatory (historically by email to the SottoSale association), so arrange it well ahead. Pair the underground tour with lunch in the village and a belvedere passeggiata.",
    maps_query: "Petralia Soprana",
    sources: ["https://www.museosottosale.it/en/an-art-museum-in-the-mine/", "https://borghipiubelliditalia.it/en/borgo/petralia-soprana/"],
  },
  {
    name: "Petralia Sottana",
    emoji: "🏘️",
    category: "towns",
    distance: "55 min drive",
    effort: "easy",
    season: "year-round",
    blurb: "Soprana's elegant twin down the hill — an Orange Flag borgo of baroque churches and cobbled lanes that doubles as the gateway town to the high Madonie.",
    details: "Petralia Sottana is one of the 'Borghi più Belli d'Italia' and holds the Touring Club's Orange Flag for hospitality; its corso threads past the Chiesa Madre and San Giovanni Battista to lookout points over the Imera valley. It's the natural service town for the southern Madonie: the road up to Piano Battaglia starts here, and the town is closely tied to the park and its UNESCO Geopark identity, with small museums covering local geology and archaeology. In August the town stages the 'Ballo della Cordella', a historic harvest dance festival, said to be one of the Madonie's most authentic traditions. Combine with Petralia Soprana, 10 minutes up the hill, and the Parco Avventura on the Piano Battaglia road for a full mountain day.",
    maps_query: "Petralia Sottana",
    sources: ["https://www.italia.it/en/sicily/petralia-sottana", "https://www.parcoavventuramadonie.it/"],
  },
  {
    name: "Gangi",
    emoji: "🌄",
    category: "towns",
    distance: "1 hr 15 min drive",
    effort: "moderate",
    season: "year-round",
    blurb: "The village that won 'most beautiful in Italy' in 2014 — a perfect cone of stone houses stacked on a hill, staring straight at Mount Etna.",
    details: "Gangi beat every other borgo in Italy in RAI's 2014 'Borgo dei Borghi' public vote, and its skyline — concentric rings of medieval houses wrapping a hilltop — is one of Sicily's great sights, best photographed from the approach road. Inside, climb to the Ventimiglia tower (now the bell tower of the Chiesa Madre), peek into some of its 18 churches, and visit Palazzo Bongiorno's frescoed halls and Palazzo Sgadari's small civic museums. Piazza del Popolo's belvedere looks over the valley, and on clear days Etna dominates the horizon. It's the farthest of the classic Madonie borghi from Gratteri, so make it a full day, ideally looping back via Geraci Siculo on the SS286. In August the Sagra della Spiga wheat festival fills the streets, and at Christmas a large living nativity takes over the old town.",
    maps_query: "Gangi, Sicily",
    sources: ["https://www.italiannotebook.com/places/gangi/", "https://www.bed-and-breakfast.it/it/news/il-borgo-dei-borghi-in-italia-e-gangi/1279"],
  },
  {
    name: "Polizzi Generosa & the world's rarest fir",
    emoji: "🌲",
    category: "towns",
    distance: "50 min drive",
    effort: "moderate",
    season: "spring-autumn",
    blurb: "A 'generous' borgo on a spur of the western Madonie, home of the sfoglio cheese-cake — and gateway to the valley hiding the ~30 last wild Madonie firs on Earth.",
    details: "Polizzi Generosa (the epithet was reputedly bestowed by Frederick II) perches dramatically above the Imera valley with churches, palazzi and big views; its culinary claim to fame is lo sfoglio, a pastry filled with fresh tuma cheese, sugar, cinnamon and chocolate that you should buy from a village pasticceria. Above town, the road towards the Quacella amphitheatre reaches the trail into the Vallone Madonna degli Angeli, where botanists in 1957 rediscovered Abies nebrodensis — the Madonie fir, thought extinct, now surviving as roughly 30 wild adult trees between 1,400 and 1,650 m and ranked among the most endangered conifers in the world. The marked 'Sentiero degli Abies nebrodensis' lets you walk among numbered, individually monitored specimens; going with a local guide adds a lot, and a small museum in town tells the species' story. Landscapes shift within a few hundred metres from holm oak to beech and holly, making this one of the park's most interesting botanical walks. Spring and autumn are best; the trail is high, so pack warm layers.",
    maps_query: "Polizzi Generosa",
    sources: ["https://www.cefalumadoniehimera.it/abies-nebrodensis/?lang=en", "https://visitpolizzigenerosa.it/it/itinerari/sentiero-abies-nebrodensis-zona-a-del-parco-delle-madonie/"],
  },

  // ---------- Coast & beaches ----------
  {
    name: "Cefalù's beaches: main sands, Caldura & the western coves",
    emoji: "🏖️",
    category: "beach",
    distance: "20-30 min drive",
    effort: "easy",
    season: "May-October",
    blurb: "One town, a whole menu of swims: a postcard sandy beach under medieval walls, a pebbly snorkel cove, and a string of half-wild coves the tourists never find.",
    details: "The main town beach along the Lungomare is long, sandy and shallow — perfect for small children, with free stretches and lidos, and the old town rising straight out of the water at its eastern end (arrive early in August). Caldura, a 20-minute walk east of the centre past the port, is gravel and dark pebbles with deep, crystal-clear water — the snorkelling spot, better with water shoes. West of town towards Gratteri, the Mazzaforno coves mix sand and pebbles among greenery with both wild corners and beach clubs, while Settefrati is named for seven rock stacks rising from the sea (local legend attached) and has superb snorkelling. Salinelle, near Capo Playa on the Lascari side, catches a steady breeze and draws wind- and kitesurfers. From Gratteri you actually reach Mazzaforno and Settefrati before Cefalù itself — handy on changeover days.",
    maps_query: "Spiaggia Settefrati Cefalù",
    sources: ["https://www.thewomtravel.com/italy/sicily/palermo/best-cefalu-beaches.html", "https://cefalu.it/en/magazine-en/the-enchanting-beauty-of-the-beaches-of-cefalu/"],
  },
  {
    name: "The long golden beach of Campofelice di Roccella",
    emoji: "🏄",
    category: "beach",
    distance: "about 20 min drive (straight downhill)",
    effort: "easy",
    season: "May-October",
    blurb: "The closest sand to Gratteri: roughly 10-12 km of golden beach running below the Lascari plain, with room to breathe even in mid-August.",
    details: "This is one of the longest beaches in Sicily, stretching from Capo Plaia near Lascari all the way to the mouth of the Imera river, with wide free sections alternating with lidos (sunbeds, showers, snack bars) around Campofelice's marina area. The sand is fine and golden, the water shallows gently, and the westward view means flaming sunsets over the mountains toward Palermo. Because it's directly below Gratteri's own plain, it's the easy 'after-school swim' beach — you can be on the sand faster than you can park in Cefalù. The Salinelle end near Capo Plaia catches more breeze and attracts windsurfers and kitesurfers. Free stretches have no facilities, so bring umbrellas and water, or pick a lido and settle in for the day.",
    maps_query: "Spiaggia Campofelice di Roccella",
    sources: ["https://www.sicilvill.com/en/experience-en-en/campofelice-di-roccella-beach/", "https://www.beachatlas.com/sand-beaches-campofelice-di-roccella"],
  },
  {
    name: "Boat trip along the Cefalù coast",
    emoji: "⛵",
    category: "beach",
    distance: "25 min drive to Cefalù port",
    effort: "easy",
    season: "roughly May-October",
    blurb: "See La Rocca and the old town from the water, then drop anchor in coves and sea caves you can't reach by road.",
    details: "Small-boat excursions leave from Cefalù's marina at Porto Presidiana, typically 3 hours with about half the time cruising past cliffs like Giudecca and Bastione and half at swim stops in bays such as Kalura, often including the Santa Lucia sea cave. Most tours include snorkel gear, fruit or a Sicilian aperitivo on board; sunset departures are the most atmospheric. Both shared and private charters exist — private skippered boats are worth it for families with young kids so you set the pace. Book a day or two ahead in July-August via the kiosks at the port or online platforms; seas are usually calmest in the morning. Bring reef-safe sunscreen and a towel per person, and check the operator's policy if the forecast turns windy.",
    maps_query: "Porto Presidiana Cefalù boat tours",
    sources: ["https://www.getyourguide.com/cefalu-l2176/cruises-boat-tours-tc48/", "https://cefaluboattours.it/en/home-en/"],
  },
  {
    name: "Sant'Ambrogio hamlet & belvedere",
    emoji: "🌅",
    category: "beach",
    distance: "about 30-35 min drive",
    effort: "easy",
    season: "year-round",
    blurb: "A tiny stone hamlet stacked above the sea just east of Cefalù — locals' quiet beach below, Madonie behind, and one of the best sunset views on this coast.",
    details: "Sant'Ambrogio is a frazione of Cefalù about 7 km east of town, a knot of alleys and stone houses around a simple village church, with a west-facing belvedere that looks straight back at Cefalù and La Rocca — go for sunset. Below the village is a gravel-and-sand beach used mostly by locals, so it stays calm even in August. There's little 'to do' in the best way: coffee in the piazza, a wander through lanes with sudden sea views, and hearty local cooking (hand-made cavatelli, local salumi and cheeses) in the couple of trattorias — check opening days outside summer. It pairs naturally with a swim at Caldura or a drive on to Castelbuono. The village feast of Sant'Ambrogio is held on 7 December if you're there in winter.",
    maps_query: "Sant'Ambrogio Cefalù belvedere",
    sources: ["https://www.bmsuitescefalu.com/en/the-village-of-santambrogio/", "https://www.taliammari.it/en/news-en/santambrogio-a-hidden-village-near-cefalu/"],
  },
  {
    name: "Torre Conca & the Finale di Pollina coast",
    emoji: "🤿",
    category: "beach",
    distance: "about 40 min drive",
    effort: "easy",
    season: "summer for swimming; walks year-round",
    blurb: "A hidden inlet under a 16th-century watchtower where the water turns deep a few steps from shore — the locals' escape when Cefalù fills up.",
    details: "Torre Conca sits just below Capo Rais Gerbi, about 1 km east of the village of Finale di Pollina; a short path drops from the coast road to a beach of sand, dark gravel and pebbles named for the old coastal watchtower above. The seabed deepens quickly, which makes it one of the best snorkelling and diving spots on this stretch, and a breakwater means you can often swim even when the open sea is choppy. Access is free with parking along the road; in summer a small snack bar appears and pedal boats are said to be for hire, but bring your own water and shade to be safe. It's popular with locals from Pollina and Finale rather than tourists. Combine with lunch in Finale or a detour up to the spectacular hilltop village of Pollina itself.",
    maps_query: "Spiaggia Torre Conca Finale di Pollina",
    sources: ["https://www.lasiciliainrete.it/en/directory-tangibili/listing/spiaggia-di-torre-conca-finale-di-pollina/", "https://cefalu.it/en/magazine-en/a-trip-along-the-coast-of-pollina-to-discover-its-beaches/"],
  },
  {
    name: "Aeolian Islands day trip (Lipari & Vulcano)",
    emoji: "🌋",
    category: "beach",
    distance: "25 min to Cefalù + full-day excursion",
    effort: "moderate",
    season: "summer only (roughly June-September)",
    blurb: "From Gratteri's belvedere you can see the Aeolians on clear days — in summer you can actually stand on them: volcanic islands, black-sand beaches and thermal mud in a single epic day.",
    details: "Cefalù historically had a seasonal summer hydrofoil to the Aeolians, but that direct scheduled service is reported suspended in recent years — verify locally before planning around it. What runs reliably in season are organized full-day excursions sold in Cefalù: typically an early start, then boat to Lipari (citadel, archaeological museum, pretty waterfront for lunch) and Vulcano (steaming fumaroles, thermal mud baths, black-sand swimming); some itineraries instead do Panarea and an evening Stromboli eruption cruise. Note some operators coach you to Milazzo to board rather than sailing from Cefalù's port — check when booking. It is a long day (roughly 12 hours) best for kids ~6+. Book several days ahead in August, take seasickness tablets if in doubt, and pack swimwear plus a change of clothes — the sulphur smell on Vulcano clings.",
    maps_query: "Cefalù port Aeolian Islands excursions",
    sources: ["https://www.viator.com/tours/Sicily/Aeolian-Islands-Lipari-and-Vulcano-Day-Tour-from-Cefalu/d205-6552P11", "https://www.tripadvisor.com/ShowTopic-g194726-i1382-k15014716-Cefalu_to_Lipari_Summer_2025-Cefalu_Province_of_Palermo_Sicily.html"],
  },

  // ---------- Food & wine ----------
  {
    name: "Wine tasting at Abbazia Santa Anastasia",
    emoji: "🍷",
    category: "food",
    distance: "about 30 min drive",
    effort: "easy",
    season: "year-round (book ahead; harvest is Sept-Oct)",
    blurb: "A 12th-century Benedictine abbey turned biodynamic wine estate in the hills between Cefalù and Castelbuono — vineyard walks, cellar tours and long tasting lunches with sea views.",
    details: "The estate covers around 400 hectares on the slopes above the coast near Castelbuono, with roughly 65 hectares of vines between 200 and 500 m altitude, and traces its winemaking legacy to Benedictine monks in the 1100s. It farms organically and biodynamically (Demeter-certified) — flagship reds like Litra sit alongside local varieties such as Nero d'Avola — and runs guided visits with vineyard walks, an explanation of biodynamics, and sommelier-led tastings, often paired with a light Sicilian lunch. There's also a relais (hotel, pool and restaurant) on site if the parents fancy a treat night. It's one of the closest serious wineries to Gratteri, making it an ideal lazy half-day. Book tastings in advance by email or through wine-tourism platforms rather than turning up; harvest season visits are especially atmospheric.",
    maps_query: "Abbazia Santa Anastasia winery Castelbuono",
    sources: ["https://www.abbaziasantanastasia.com/en/", "https://www.winerytastingsicily.com/producer/abbazia-santa-anastasia-castelbuono-palermo-cefalu/"],
  },
  {
    name: "Castelbuono food trail: Fiasconaro, manna & Madonie cheese",
    emoji: "🧁",
    category: "food",
    distance: "about 35-40 min drive",
    effort: "easy",
    season: "year-round (manna harvest July-Sept)",
    blurb: "The Madonie's gourmet capital: the pasticceria that made Castelbuono's panettone world-famous, tree sap harvested like nowhere else in Europe, and a castle thrown in.",
    details: "Start in Piazza Margherita at Fiasconaro, the family pasticceria founded in 1953 whose naturally-leavened panettone and colomba are now exported worldwide — sit down for cannoli, cassata, sfince with ricotta and a gelato, and buy an 'Oro di Manna' panettone to take home. Manna is the local marvel: the crystallised sap of manna ash trees, tapped only between Castelbuono and Pollina in late summer, forming white 'cannoli' stalactites on threads — look for manna sweets and spreads in town shops. Hunt out provola delle Madonie, a Slow Food Presidium flask-shaped cow's-milk cheese from semi-wild mountain herds, in local delis and on trattoria boards. Then visit the 1317 Ventimiglia castle and the Matrice Vecchia to walk it all off. In Cefalù itself, locals rate the family-run pasticcerias near the station for cannoli — ask an ambassador for their favourite and add it to the tips!",
    maps_query: "Pasticceria Fiasconaro Castelbuono",
    sources: ["https://fiasconaro.com/en/manna-our-treasure/", "https://www.fondazioneslowfood.com/en/slow-food-presidia/madonie-provola/"],
  },

  // ---------- Day trips ----------
  {
    name: "Cefalù old town & Arab-Norman Duomo",
    emoji: "⛪",
    category: "daytrip",
    distance: "25 min drive",
    effort: "easy",
    season: "year-round",
    blurb: "Your 'local' town is a UNESCO World Heritage showstopper: a Norman cathedral with the finest Byzantine Christ Pantocrator mosaic in Italy, wrapped in a fishing-village old town.",
    details: "The Duomo was begun in 1131 after King Roger II survived a storm at sea, and Byzantine masters from Constantinople finished the apse mosaics before 1170 — the Pantocrator holds a gospel reading 'I am the light of the world' in Greek and Latin. It is part of the UNESCO Arab-Norman Palermo/Cefalù/Monreale site, and its pilaster decoration echoes Gratteri's own San Giorgio abbey, built in the same years. Afterwards wander Corso Ruggero and the lanes down to the sea: find the Lavatoio Medievale, a sunken medieval-origin washhouse where the Cefalino river gushes from 22 cast-iron spouts (free, reached by a polished lava-stone staircase), and Porta Pescara, the only surviving medieval sea gate, whose Gothic arch frames the fishing boats — the classic photo. Go early morning or late afternoon in summer; shoulders and knees covered inside the cathedral. Combine with a swim off the old-town beach and dinner on the harbour wall.",
    maps_query: "Duomo di Cefalù",
    sources: ["https://whc.unesco.org/en/list/1487/", "https://cefalu.it/en/magazine-en/the-medieval-wash-house-of-cefalu/"],
  },
  {
    name: "La Rocca climb & Temple of Diana",
    emoji: "🥾",
    category: "daytrip",
    distance: "25 min drive + 45-60 min climb",
    effort: "challenging",
    season: "year-round (avoid midday in summer)",
    blurb: "The great crag looming over Cefalù hides a megalithic temple, a Norman-era castle and a 360° panorama over the red rooftops, the Duomo and the Tyrrhenian.",
    details: "The path (Salita Saraceni) starts near Corso Ruggero and zigzags up through three tiers of old city walls; allow 30-45 minutes to the top and 1.5-2 hours total. Halfway up sits the so-called Temple of Diana, a megalithic structure said to date to the 9th-8th century BC, and the summit holds the ruins of a 13th-century castle with sweeping views of town, coast and the Madonie. There is almost no shade, so start before 9:30 in summer and carry at least a litre of water each; proper shoes beat sandals on the loose gravel sections. There is a small entry fee to the archaeological park (check locally for hours). Great with older kids; not buggy-friendly. Sunset light on the bay is spectacular but check closing times before planning an evening climb.",
    maps_query: "La Rocca di Cefalù Salita Saraceni",
    sources: ["https://www.visitcefalu.com/en/rocca-di-cefalu/", "https://www.alltrails.com/trail/italy/sicily/la-rocca-cefalu"],
  },
  {
    name: "Himera: Temple of Victory & Antiquarium",
    emoji: "🏛️",
    category: "daytrip",
    distance: "about 30 min drive",
    effort: "easy",
    season: "year-round (spring and autumn are loveliest)",
    blurb: "Stand where Greeks crushed a Carthaginian invasion in 480 BC — archaeologists found the soldiers' mass graves here, and the temple built to celebrate the victory still stands in a field by the sea.",
    details: "Himera was a Greek colony founded in 648 BC at the mouth of the Imera river, just west of Campofelice — you pass it on the way to Palermo. The Doric Temple of Victory (c. 480-470 BC) is traditionally linked to the great Battle of Himera of 480 BC, when a Greek coalition under Gelon of Syracuse defeated Carthage; recent excavations of the western necropolis uncovered mass graves of warriors from the battles of 480 and 409 BC. The upper town preserves the sanctuary of Athena and street grid, and the Antiquarium 'Pirro Marconi' museum displays finds including a cast of a mass-grave skeleton, a horse skull with bronze bit, and weapons bent by battle impact — genuinely gripping for kids. The site is rarely busy, so you often have it nearly to yourself. Little shade in summer: hats and water. Check locally for current opening days before driving over.",
    maps_query: "Parco Archeologico di Himera Antiquarium",
    sources: ["https://en.wikipedia.org/wiki/Temple_of_Victory_(Himera)", "https://www.italia.it/en/sicilia/termini-imerese/cultural-places/himera-archaeological-area"],
  },
  {
    name: "Caccamo Castle",
    emoji: "🏰",
    category: "daytrip",
    distance: "about 50 min drive",
    effort: "easy",
    season: "year-round",
    blurb: "One of the largest and best-preserved Norman castles in Sicily — a white-stone fortress on a cliff, complete with battlements, a conspiracy hall and a weapons museum.",
    details: "Castello di Caccamo crowns a crag 521 m up, overlooking the San Leonardo valley and the Rosmarina lake, and is counted among the biggest castles in Italy. Its core was built in the 12th century by Matteo Bonello and extended by the Chiaramonte family in the 14th; the famous Sala della Congiura is where Norman barons plotted their failed 1160 revolt against King William I. Inside is a maze of rooms, stairways and ramparts with V-shaped battlements, plus a museum of ancient weapons that lands well with children. A restaurant occupies the old stables at ground level, and the town below has fine churches around the Chiesa Madre. It's an easy half-day, best combined with Himera or Termini Imerese on the way; check locally for opening days and guided-visit times.",
    maps_query: "Castello di Caccamo",
    sources: ["https://en.wikipedia.org/wiki/Castello_di_Caccamo", "https://www.visitsicily.info/en/castle-of-caccamo/"],
  },
  {
    name: "Palermo: Cappella Palatina, markets & street food",
    emoji: "🍋",
    category: "daytrip",
    distance: "1h15 drive (or train from Cefalù)",
    effort: "moderate",
    season: "year-round (spring/autumn ideal; hot in August)",
    blurb: "Sicily's chaotic, glorious capital: a golden Byzantine chapel built for a Norman king, then souk-like markets where lunch is fried chickpea fritters eaten standing up.",
    details: "Do the Palazzo dei Normanni first thing: the Cappella Palatina, commissioned by Roger II in 1132, fuses Byzantine gold mosaics, Arab muqarnas ceilings and Norman architecture — book timed tickets in advance as slots sell out on peak dates. Then dive into the markets: Ballarò is the oldest and most raucous, Capo slightly calmer with excellent street food. Eat as Palermitans do: pane e panelle (chickpea fritter sandwich), arancine, sfincione (spongy onion-and-tomato Sicilian pizza), and for the brave, stigghiola from a smoking grill. Fit in the Quattro Canti, the cathedral and Teatro Massimo facade on a walking loop. Consider the train from Cefalù (roughly an hour) to skip city parking entirely — Palermo driving is not for the faint-hearted. Keep valuables zipped in the market crush, and go on a weekday morning for the full show.",
    maps_query: "Cappella Palatina Palazzo dei Normanni Palermo",
    sources: ["https://www.lonelyplanet.com/articles/top-things-to-do-in-palermo-sicily", "https://whc.unesco.org/en/list/1487/"],
  },
  {
    name: "Monreale cathedral & cloister",
    emoji: "✨",
    category: "daytrip",
    distance: "about 1h30 drive (just beyond Palermo)",
    effort: "easy",
    season: "year-round",
    blurb: "Around 6,000 square metres of gold mosaics telling the whole Bible in pictures — the grand finale of the same UNESCO Arab-Norman trio as your local Cefalù Duomo.",
    details: "William II's cathedral above Palermo is carpeted in some of the most extensive Byzantine-style mosaics in existence, crowned by a colossal apse Pantocrator whose outstretched arms seem to embrace the nave — compare it with Cefalù's and let the kids vote. Don't skip the Benedictine cloister: 228 paired columns, each capital carved differently with beasts, saints and patterns; it's a separate ticket from the cathedral. Climbing to the roof terraces earns views over the Conca d'Oro valley to Palermo and a look down into the cloister. Go early on a weekday and avoid Sunday mornings; shoulders and knees must be covered (carry a scarf in summer). Easiest done as the morning half of a Palermo day — park in Monreale or take the city bus up from Palermo — with mosaics before the crowds, then markets for lunch.",
    maps_query: "Duomo di Monreale",
    sources: ["https://en.wikipedia.org/wiki/Monreale_Cathedral", "https://wearepalermo.com/news/visit-cathedral-of-monreale/"],
  },
];
